#!/usr/bin/env python3
"""Generate Rust kernel embedding, structs, and load methods from JSON metadata.

Reads kernel_configs.py (KERNEL_METADATA) and out/ttir/*.json to produce:
  - out/generated/triton_metal_gen.rs  (Metal: kernel_data + structs + load)
  - out/generated/triton_d3d12_gen.rs  (D3D12: DXIL consts + structs + load)

Called from build.py after ninja completes.
"""
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUT = SCRIPT_DIR / "out"
GEN_DIR = OUT / "generated"


def write_if_changed(path: Path, content: str) -> bool:
    """Write only if content differs, preserving mtime for cargo."""
    if path.exists():
        try:
            if path.read_text() == content:
                return False
        except Exception:
            pass
    path.write_text(content)
    return True


def load_metadata():
    """Import KERNEL_METADATA and kernel lists from kernel_configs.py."""
    sys.path.insert(0, str(SCRIPT_DIR))
    from kernel_configs import KERNEL_METADATA, METAL_KERNELS, HLSL_EXTRA_KERNELS
    return KERNEL_METADATA, METAL_KERNELS, HLSL_EXTRA_KERNELS


def load_kokoro_kernels():
    """Import Kokoro kernel configs."""
    sys.path.insert(0, str(SCRIPT_DIR))
    from kokoro_configs import KOKORO_KERNELS
    return KOKORO_KERNELS


def read_json(name):
    """Read TTIR JSON metadata for a kernel, return dict or None."""
    p = OUT / "ttir" / f"{name}.json"
    if p.exists():
        return json.loads(p.read_text())
    return None


def gen_metal(metadata, metal_kernels):
    """Generate triton_metal_gen.rs: kernel_data + TritonKernels + DecoderKernels."""
    lines = []
    lines.append("// Auto-generated by gen_rust.py -- do not edit")
    lines.append("")

    # Collect all metal kernel names (order matters for struct fields)
    metal_names = [cfg[0] for cfg in metal_kernels]

    # Partition into encoder and decoder groups
    encoder_kernels = []
    decoder_kernels = []
    for name in metal_names:
        meta = metadata.get(name)
        if not meta:
            continue
        group = meta.get("group", "encoder")
        if group == "decoder":
            decoder_kernels.append(name)
        else:
            encoder_kernels.append(name)

    # include_bytes! paths are relative to the file containing the macro,
    # which is kernels/out/generated/triton_metal_gen.rs.
    # So ../metal/ means kernels/out/metal/.

    # ── kernel_data module (aarch64) ──
    lines.append("#[cfg(target_arch = \"aarch64\")]")
    lines.append("mod kernel_data {")
    lines.append("    pub fn load_kernel(name: &str) -> Option<&'static [u8]> {")
    lines.append("        match name {")
    for name in metal_names:
        path = f"../metal/{name}.metallib"
        lines.append(f'            "{name}" => Some(include_bytes!("{path}")),')
    lines.append("            _ => None,")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # ── kernel_data module (x86_64) ──
    lines.append("#[cfg(target_arch = \"x86_64\")]")
    lines.append("mod kernel_data {")
    lines.append("    pub fn load_kernel(name: &str) -> Option<&'static [u8]> {")
    lines.append("        match name {")
    for name in metal_names:
        path = f"../metal_nosimd/{name}.metallib"
        lines.append(f'            "{name}" => Some(include_bytes!("{path}")),')
    lines.append("            _ => None,")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # ── TritonKernels struct ──
    lines.append("/// All compiled Triton kernel pipelines for the Moonshine encoder.")
    lines.append("pub struct TritonKernels {")
    for name in encoder_kernels:
        meta = metadata[name]
        alias = meta["alias"]
        optional = meta.get("optional", False)
        typ = "Option<ComputePipeline>" if optional else "ComputePipeline"
        lines.append(f"    pub {alias}: {typ},")
    lines.append("}")
    lines.append("")

    # ── TritonKernels::load() ──
    lines.append("impl TritonKernels {")
    lines.append("    pub fn load(metal_device: &MetalDevice) -> Result<Self> {")
    lines.append("        let device = metal_device.device();")
    lines.append("")
    lines.append("        let load = |name: &str, func_name: &str| -> Result<ComputePipeline> {")
    lines.append("            eprint!(\"    {name}...\");")
    lines.append("            let data = kernel_data::load_kernel(name)")
    lines.append("                .ok_or_else(|| anyhow::anyhow!(\"No embedded kernel for {name}\"))?;")
    lines.append("            let lib = device.new_library_with_data(data)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Failed to load metallib {name}: {e}\"))?;")
    lines.append("            let func = lib")
    lines.append("                .get_function(func_name, None)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Function {func_name} not found in {name}: {e}\"))?;")
    lines.append("            let pipeline = device")
    lines.append("                .new_compute_pipeline_state_with_function(&func)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Pipeline failed for {name}: {e}\"))?;")
    lines.append("            eprintln!(\" ok (max_threads={})\", pipeline.max_total_threads_per_threadgroup());")
    lines.append("            Ok(pipeline)")
    lines.append("        };")
    lines.append("")
    lines.append("        Ok(Self {")
    for name in encoder_kernels:
        meta = metadata[name]
        alias = meta["alias"]
        optional = meta.get("optional", False)
        # Read func_name from the kernel config
        func_name = _get_func_name(name, metal_kernels)
        if optional:
            lines.append(f'            {alias}: {{')
            lines.append(f'                match load("{name}", "{func_name}") {{')
            lines.append(f'                    Ok(p) => Some(p),')
            lines.append(f'                    Err(e) => {{ eprintln!(" SKIP ({{e}})"); None }}')
            lines.append(f'                }}')
            lines.append(f'            }},')
        else:
            lines.append(f'            {alias}: load("{name}", "{func_name}")?,')
    lines.append("        })")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # ── DecoderKernels struct ──
    lines.append("/// All compiled Triton kernel pipelines for the Moonshine decoder.")
    lines.append("pub struct DecoderKernels {")
    for name in decoder_kernels:
        meta = metadata[name]
        alias = meta["alias"]
        optional = meta.get("optional", False)
        typ = "Option<ComputePipeline>" if optional else "ComputePipeline"
        lines.append(f"    pub {alias}: {typ},")
    # Also include matmul_32x32 from encoder set (decoder reuses it)
    lines.append("    pub matmul_32x32: ComputePipeline,")
    lines.append("}")
    lines.append("")

    # ── DecoderKernels::load() ──
    lines.append("impl DecoderKernels {")
    lines.append("    pub fn load(metal_device: &MetalDevice) -> Result<Self> {")
    lines.append("        let device = metal_device.device();")
    lines.append("")
    lines.append("        let load = |name: &str, func_name: &str| -> Result<ComputePipeline> {")
    lines.append("            eprint!(\"    {name}...\");")
    lines.append("            let data = kernel_data::load_kernel(name)")
    lines.append("                .ok_or_else(|| anyhow::anyhow!(\"No embedded kernel for {name}\"))?;")
    lines.append("            let lib = device.new_library_with_data(data)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Failed to load metallib {name}: {e}\"))?;")
    lines.append("            let func = lib")
    lines.append("                .get_function(func_name, None)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Function {func_name} not found in {name}: {e}\"))?;")
    lines.append("            let pipeline = device")
    lines.append("                .new_compute_pipeline_state_with_function(&func)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Pipeline failed for {name}: {e}\"))?;")
    lines.append("            eprintln!(\" ok (max_threads={})\", pipeline.max_total_threads_per_threadgroup());")
    lines.append("            Ok(pipeline)")
    lines.append("        };")
    lines.append("")
    lines.append("        Ok(Self {")
    for name in decoder_kernels:
        meta = metadata[name]
        alias = meta["alias"]
        optional = meta.get("optional", False)
        func_name = _get_func_name(name, metal_kernels)
        if optional:
            lines.append(f'            {alias}: load("{name}", "{func_name}").ok(),')
        else:
            lines.append(f'            {alias}: load("{name}", "{func_name}")?,')
    # matmul_32x32 from encoder kernel set
    lines.append(f'            matmul_32x32: load("matmul_bias_fp16_32x32x32", "matmul_bias_fp16")?,')
    lines.append("        })")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def gen_d3d12(metadata, metal_kernels, hlsl_extra):
    """Generate triton_d3d12_gen.rs: DXIL consts + structs + load."""
    lines = []
    lines.append("// Auto-generated by gen_rust.py -- do not edit")
    lines.append("")

    # Collect all d3d12 kernels from metadata
    # Use the combined kernel list order
    all_names = []
    seen = set()
    for cfg in metal_kernels:
        name = cfg[0]
        if name not in seen:
            seen.add(name)
            all_names.append(name)
    for cfg in hlsl_extra:
        name = cfg[0]
        if name not in seen:
            seen.add(name)
            all_names.append(name)

    d3d12_kernels = []
    for name in all_names:
        meta = metadata.get(name)
        if meta and meta.get("d3d12"):
            d3d12_kernels.append(name)

    # Partition into encoder and decoder
    d3d12_encoder = [n for n in d3d12_kernels if metadata[n].get("group") == "encoder"]
    d3d12_decoder = [n for n in d3d12_kernels if metadata[n].get("group") == "decoder"]

    # ── DXIL constants (encoder only; decoder has hand-written consts) ──
    # Paths relative to kernels/out/generated/triton_d3d12_gen.rs
    for name in d3d12_encoder:
        meta = metadata[name]
        alias = meta["alias"]
        const_name = f"DXIL_{alias.upper()}"
        lines.append(f'const {const_name}: &[u8] = include_bytes!("../dxil/{name}.dxil");')
    lines.append("")

    # ── TritonD3D12Kernels struct ──
    lines.append("/// All compiled Triton D3D12 kernel pipelines for the encoder.")
    lines.append("pub struct TritonD3D12Kernels {")
    lines.append("    pub(crate) gpu: Arc<Gpu>,")
    for name in d3d12_encoder:
        meta = metadata[name]
        alias = meta["alias"]
        optional = meta.get("optional", False)
        typ = "Option<ID3D12PipelineState>" if optional else "ID3D12PipelineState"
        lines.append(f"    pub(crate) {alias}: {typ},")
    lines.append("    pub prefer_fp16_acc: bool,")
    lines.append("}")
    lines.append("")

    # ── TritonD3D12Kernels::load() ──
    lines.append("impl TritonD3D12Kernels {")
    lines.append("    pub fn load(gpu: &Arc<Gpu>, use_fp16_acc: bool) -> Result<Self> {")
    lines.append("        let load_pso = |name: &str, dxil: &[u8]| -> Result<ID3D12PipelineState> {")
    lines.append("            gpu.create_compute_pso(dxil)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Failed to create PSO for {name}: {e}\"))")
    lines.append("        };")
    lines.append("")
    lines.append("        Ok(Self {")
    lines.append("            gpu: gpu.clone(),")
    for name in d3d12_encoder:
        meta = metadata[name]
        alias = meta["alias"]
        optional = meta.get("optional", False)
        const_name = f"DXIL_{alias.upper()}"
        if optional:
            # Some optional kernels are conditional on fp16_acc
            if "acc16" in alias:
                lines.append(f'            {alias}: if use_fp16_acc {{')
                lines.append(f'                load_pso("{name}", {const_name}).ok()')
                lines.append(f'            }} else {{ None }},')
            else:
                lines.append(f'            {alias}: load_pso("{name}", {const_name}).ok(),')
        else:
            lines.append(f'            {alias}: load_pso("{name}", {const_name})?,')
    lines.append("            prefer_fp16_acc: use_fp16_acc,")
    lines.append("        })")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # ── D3D12 Decoder: DXIL constants ──
    lines.append("// ── Decoder kernels ──")
    lines.append("")
    for name in d3d12_decoder:
        meta = metadata[name]
        alias = meta["alias"]
        const_name = f"DXIL_DEC_{alias.upper()}"
        lines.append(f'const {const_name}: &[u8] = include_bytes!("../dxil/{name}.dxil");')
    # Decoder also uses the f32-weight matmul for cross-attention KV projection
    lines.append('const DXIL_DEC_MATMUL_F32W_64: &[u8] = include_bytes!("../dxil/matmul_f16a_f32w_64x64x32.dxil");')
    lines.append("")

    # ── D3D12DecoderKernels struct ──
    lines.append("/// All compiled Triton D3D12 kernel pipelines for the Moonshine decoder.")
    lines.append("pub struct D3D12DecoderKernels {")
    lines.append("    pub(crate) gpu: Arc<Gpu>,")
    for name in d3d12_decoder:
        meta = metadata[name]
        alias = meta["alias"]
        lines.append(f"    pub(crate) {alias}: ID3D12PipelineState,")
    lines.append("    pub(crate) matmul_f32w_64: ID3D12PipelineState,")
    lines.append("}")
    lines.append("")

    # ── D3D12DecoderKernels::load() ──
    lines.append("impl D3D12DecoderKernels {")
    lines.append("    pub fn load(gpu: &Arc<Gpu>) -> Result<Self> {")
    lines.append("        let load_pso = |name: &str, dxil: &[u8]| -> Result<ID3D12PipelineState> {")
    lines.append("            gpu.create_compute_pso(dxil)")
    lines.append('                .map_err(|e| anyhow::anyhow!("Failed to create PSO for {name}: {e}"))')
    lines.append("        };")
    lines.append("")
    lines.append("        Ok(Self {")
    lines.append("            gpu: gpu.clone(),")
    for name in d3d12_decoder:
        meta = metadata[name]
        alias = meta["alias"]
        const_name = f"DXIL_DEC_{alias.upper()}"
        lines.append(f'            {alias}: load_pso("{name}", {const_name})?,')
    lines.append('            matmul_f32w_64: load_pso("matmul_f16a_f32w_64x64x32", DXIL_DEC_MATMUL_F32W_64)?,')
    lines.append("        })")
    lines.append("    }")
    lines.append("")

    # ── Generated dispatch methods ──
    # Each method encodes root constants + UAV bindings from TTIR JSON metadata.
    lines.append("    #[allow(unused_parens)]")
    for name in d3d12_decoder:
        meta = metadata[name]
        alias = meta["alias"]
        ttir = read_json(name)
        if not ttir:
            continue

        # Separate pointer params (→ UAVs) and scalar params (→ root constants)
        ptrs = [p for p in ttir["params"] if p["is_pointer"]]
        scalars = [p for p in ttir["params"] if not p["is_pointer"]]

        # Convert param names to snake_case for Rust
        def to_snake(name):
            import re
            # Insert _ before uppercase letters, then lowercase
            s1 = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', name)
            s2 = re.sub(r'([a-z\d])([A-Z])', r'\1_\2', s1)
            return s2.lower()

        # Build Rust function signature
        fn_args = []
        for p in ptrs:
            sn = to_snake(p['name'])
            fn_args.append(f"{sn}: &GpuBuffer, {sn}_count: u32")
        for p in scalars:
            sn = to_snake(p['name'])
            if p["type"] == "fp32":
                fn_args.append(f"{sn}: f32")
            else:
                fn_args.append(f"{sn}: i32")

        lines.append(f"    pub fn dispatch_{alias}(&self, {', '.join(fn_args)}) -> Result<()> {{")

        # Grid computation
        grid_exprs = ttir["grid"]
        for i, expr in enumerate(grid_exprs):
            axis = ["x", "y", "z"][i]
            rust_expr = expr
            if "cdiv(" in rust_expr:
                import re
                rust_expr = re.sub(
                    r'cdiv\((\w+),\s*(\d+)\)',
                    lambda m: f"({to_snake(m.group(1))} as u32 + {int(m.group(2))-1}) / {m.group(2)}",
                    rust_expr
                )
            else:
                rust_expr = f"{to_snake(rust_expr)} as u32"
            lines.append(f"        let grid_{axis} = {rust_expr};")

        # Root constants: scalars first, then grid dims
        lines.append("        let rc: Vec<u32> = vec![")
        for p in scalars:
            sn = to_snake(p['name'])
            if p["type"] == "fp32":
                lines.append(f"            {sn}.to_bits(),")
            else:
                lines.append(f"            {sn} as u32,")
        lines.append("            grid_x, grid_y, grid_z,")
        lines.append("        ];")

        # UAV bindings
        lines.append("        let uavs = [")
        for p in ptrs:
            sn = to_snake(p['name'])
            if "fp32" in p["type"] or "f32" in p["type"]:
                lines.append(f"            BufferBinding::structured_f32({sn}, {sn}_count),")
            else:
                lines.append(f"            BufferBinding::structured_f16({sn}, {sn}_count),")
        lines.append("        ];")

        lines.append(f'        self.gpu.record_dispatch(&self.{alias}, &rc, &uavs, [grid_x, grid_y, grid_z])')
        lines.append(f'            .map_err(|e| anyhow::anyhow!("{alias}: {{e}}"))')
        lines.append("    }")
        lines.append("")

    # Add matmul_f32w dispatch (not in decoder metadata, hand-add)
    lines.append("    pub fn dispatch_matmul_f32w(&self, a: &GpuBuffer, a_count: u32,")
    lines.append("                                b: &GpuBuffer, b_count: u32,")
    lines.append("                                out: &GpuBuffer, out_count: u32,")
    lines.append("                                m: i32, n: i32, k: i32) -> Result<()> {")
    lines.append("        let grid_x = (m as u32 + 63) / 64;")
    lines.append("        let grid_y = (n as u32 + 63) / 64;")
    lines.append("        let rc: Vec<u32> = vec![")
    lines.append("            m as u32, n as u32, k as u32,")
    lines.append("            k as u32, 1, n as u32, 1,")
    lines.append("            n as u32, 1, grid_x, grid_y, 1,")
    lines.append("        ];")
    lines.append("        let uavs = [")
    lines.append("            BufferBinding::structured_f16(a, a_count),")
    lines.append("            BufferBinding::structured_f32(b, b_count),")
    lines.append("            BufferBinding::structured_f16(out, out_count),")
    lines.append("        ];")
    lines.append('        self.gpu.record_dispatch(&self.matmul_f32w_64, &rc, &uavs, [grid_x, grid_y, 1])')
    lines.append('            .map_err(|e| anyhow::anyhow!("matmul_f32w: {e}"))')
    lines.append("    }")

    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def _get_func_name(kernel_name, kernel_list):
    """Get the @triton.jit function name for a kernel from its config."""
    for cfg in kernel_list:
        if cfg[0] == kernel_name:
            return cfg[1]
    # Fallback: kernel_name itself
    return kernel_name


def gen_kokoro_metal(metadata, kokoro_kernels):
    """Generate kokoro_metal_gen.rs: kernel_data + KokoroKernels + load."""
    lines = []
    lines.append("// Auto-generated by gen_rust.py -- do not edit")
    lines.append("")

    kokoro_names = [cfg[0] for cfg in kokoro_kernels]
    # Include shared matmul kernel needed by kokoro (plain matmul, no bias)
    shared_kernels = ["matmul_fp16_64x64x32"]

    # kernel_data — aarch64
    lines.append('#[cfg(target_arch = "aarch64")]')
    lines.append("mod kernel_data {")
    lines.append("    pub fn load_kernel(name: &str) -> Option<&'static [u8]> {")
    lines.append("        match name {")
    for name in kokoro_names:
        lines.append(f'            "{name}" => Some(include_bytes!("../metal/{name}.metallib")),')
    for name in shared_kernels:
        lines.append(f'            "{name}" => Some(include_bytes!("../metal/{name}.metallib")),')
    lines.append("            _ => None,")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # kernel_data — x86_64
    lines.append('#[cfg(target_arch = "x86_64")]')
    lines.append("mod kernel_data {")
    lines.append("    pub fn load_kernel(name: &str) -> Option<&'static [u8]> {")
    lines.append("        match name {")
    for name in kokoro_names:
        lines.append(f'            "{name}" => Some(include_bytes!("../metal_nosimd/{name}.metallib")),')
    for name in shared_kernels:
        lines.append(f'            "{name}" => Some(include_bytes!("../metal_nosimd/{name}.metallib")),')
    lines.append("            _ => None,")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # KokoroKernels struct
    lines.append("/// Compiled Triton kernel pipelines for the Kokoro TTS decoder.")
    lines.append("pub struct KokoroKernels {")
    for name in kokoro_names:
        meta = metadata.get(name)
        if meta:
            lines.append(f"    pub {meta['alias']}: ComputePipeline,")
    lines.append("    pub matmul: ComputePipeline,")
    lines.append("}")
    lines.append("")

    # KokoroKernels::load()
    lines.append("impl KokoroKernels {")
    lines.append("    pub fn load(metal_device: &MetalDevice) -> Result<Self> {")
    lines.append("        let device = metal_device.device();")
    lines.append("")
    lines.append("        let load = |name: &str, func_name: &str| -> Result<ComputePipeline> {")
    lines.append("            let data = kernel_data::load_kernel(name)")
    lines.append("                .ok_or_else(|| anyhow::anyhow!(\"No embedded kernel for {name}\"))?;")
    lines.append("            let lib = device.new_library_with_data(data)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Failed to load metallib {name}: {e}\"))?;")
    lines.append("            let func = lib")
    lines.append("                .get_function(func_name, None)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Function {func_name} not found in {name}: {e}\"))?;")
    lines.append("            let pipeline = device")
    lines.append("                .new_compute_pipeline_state_with_function(&func)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Pipeline failed for {name}: {e}\"))?;")
    lines.append("            Ok(pipeline)")
    lines.append("        };")
    lines.append("")
    lines.append("        Ok(Self {")
    for cfg in kokoro_kernels:
        name = cfg[0]
        func_name = cfg[1]
        meta = metadata.get(name)
        if meta:
            lines.append(f'            {meta["alias"]}: load("{name}", "{func_name}")?,')
    lines.append(f'            matmul: load("matmul_fp16_64x64x32", "matmul_fp16")?,')
    lines.append("        })")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def gen_kokoro_d3d12(metadata, kokoro_kernels):
    """Generate kokoro_d3d12_gen.rs: DXIL consts + KokoroD3D12Kernels + load."""
    dxil_dir = OUT / "dxil"
    lines = []
    lines.append("// Auto-generated by gen_rust.py -- do not edit")
    lines.append("")

    # DXIL constants
    for cfg in kokoro_kernels:
        name = cfg[0]
        meta = metadata.get(name)
        if not meta or not meta.get("d3d12"):
            continue
        if not (dxil_dir / f"{name}.dxil").exists():
            continue
        const_name = f"DXIL_KOKORO_{meta['alias'].upper()}"
        lines.append(f'const {const_name}: &[u8] = include_bytes!("../dxil/{name}.dxil");')
    # Shared matmul kernel (plain, no bias — used with row_bias_add for conv1d)
    if (dxil_dir / "matmul_fp16_64x64x32.dxil").exists():
        lines.append(f'const DXIL_MATMUL_64X64: &[u8] = include_bytes!("../dxil/matmul_fp16_64x64x32.dxil");')
    lines.append("")

    # KokoroD3D12Kernels struct
    lines.append("pub struct KokoroD3D12Kernels {")
    for cfg in kokoro_kernels:
        name = cfg[0]
        meta = metadata.get(name)
        if not meta or not meta.get("d3d12"):
            continue
        if not (dxil_dir / f"{name}.dxil").exists():
            continue
        lines.append(f"    pub(crate) {meta['alias']}: ID3D12PipelineState,")
    lines.append("    pub(crate) matmul: ID3D12PipelineState,")
    lines.append("}")
    lines.append("")

    # load()
    lines.append("impl KokoroD3D12Kernels {")
    lines.append("    pub fn load(gpu: &Arc<Gpu>) -> Result<Self> {")
    lines.append("        let load_pso = |name: &str, dxil: &[u8]| -> Result<ID3D12PipelineState> {")
    lines.append("            gpu.create_compute_pso(dxil)")
    lines.append('                .map_err(|e| anyhow::anyhow!("Failed to create PSO for {name}: {e}"))')
    lines.append("        };")
    lines.append("")
    lines.append("        Ok(Self {")
    for cfg in kokoro_kernels:
        name = cfg[0]
        meta = metadata.get(name)
        if not meta or not meta.get("d3d12"):
            continue
        if not (dxil_dir / f"{name}.dxil").exists():
            continue
        const_name = f"DXIL_KOKORO_{meta['alias'].upper()}"
        lines.append(f'            {meta["alias"]}: load_pso("{name}", {const_name})?,')
    lines.append(f'            matmul: load_pso("matmul_fp16_64x64x32", DXIL_MATMUL_64X64)?,')
    lines.append("        })")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def main():
    metadata, metal_kernels, hlsl_extra = load_metadata()
    kokoro_kernels = load_kokoro_kernels()

    GEN_DIR.mkdir(parents=True, exist_ok=True)

    metal_code = gen_metal(metadata, metal_kernels)
    write_if_changed(GEN_DIR / "triton_metal_gen.rs", metal_code)

    d3d12_code = gen_d3d12(metadata, metal_kernels, hlsl_extra)
    write_if_changed(GEN_DIR / "triton_d3d12_gen.rs", d3d12_code)

    kokoro_metal_code = gen_kokoro_metal(metadata, kokoro_kernels)
    write_if_changed(GEN_DIR / "kokoro_metal_gen.rs", kokoro_metal_code)

    kokoro_d3d12_code = gen_kokoro_d3d12(metadata, kokoro_kernels)
    write_if_changed(GEN_DIR / "kokoro_d3d12_gen.rs", kokoro_d3d12_code)

    # Count
    metal_enc = sum(1 for m in metadata.values() if m.get("group") == "encoder" and not m.get("d3d12_only"))
    metal_dec = sum(1 for m in metadata.values() if m.get("group") == "decoder" and not m.get("d3d12_only"))
    d3d12_enc = sum(1 for m in metadata.values() if m.get("d3d12") and m.get("group") == "encoder")
    d3d12_dec = sum(1 for m in metadata.values() if m.get("d3d12") and m.get("group") == "decoder")
    kokoro_n = sum(1 for m in metadata.values() if m.get("group") == "kokoro")
    print(f"gen_rust: Metal {metal_enc} enc + {metal_dec} dec, D3D12 {d3d12_enc} enc + {d3d12_dec} dec, Kokoro {kokoro_n}")


if __name__ == "__main__":
    main()
