/// Quantized weight loader for NPZ format
///
/// Loads Q8_0 and Q4_0 quantized weights from NPZ files generated by quantize_parakeet.py
use anyhow::{anyhow, Result};
use candle_core::{Device, Tensor};
use half::f16;
use npyz::npz::NpzArchive;
use std::collections::HashMap;
use std::fs::File;
use std::io::BufReader;

/// Quantization type matching Python script
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum QuantType {
    F32 = 0,
    Q8_0 = 8,
    Q4_0 = 2,
}

impl QuantType {
    fn from_i32(v: i32) -> Result<Self> {
        match v {
            0 => Ok(QuantType::F32),
            8 => Ok(QuantType::Q8_0),
            2 => Ok(QuantType::Q4_0),
            _ => Err(anyhow!("Unknown quantization type: {}", v)),
        }
    }
}

/// Quantized weight information
#[derive(Debug, Clone)]
struct QuantizedWeight {
    qtype: QuantType,
    shape: Vec<usize>,
    data: Vec<u8>, // Raw bytes for scales + qweights
}

/// Quantized weight loader
pub struct QuantizedLoader {
    weights: HashMap<String, QuantizedWeight>,
    device: Device,
}

impl QuantizedLoader {
    /// Load quantized weights from NPZ file
    pub fn from_npz(path: &str, device: Device) -> Result<Self> {
        let file = File::open(path)?;
        let reader = BufReader::new(file);
        let mut npz = NpzArchive::new(reader)?;

        let mut weights = HashMap::new();
        let mut tensor_names = std::collections::HashSet::new();

        // First pass: collect all tensor names
        for name in npz.array_names() {
            if let Some(tensor_name) = name.strip_suffix("||type") {
                tensor_names.insert(tensor_name.to_string());
            }
        }

        // Second pass: load each tensor
        for tensor_name in tensor_names {
            let type_key = format!("{}||type", tensor_name);
            let shape_key = format!("{}||shape", tensor_name);

            // Read type
            let qtype_arr = npz.by_name(&type_key)?
                .ok_or_else(|| anyhow!("Missing type for {}", tensor_name))?;
            let qtype_data: Vec<i32> = qtype_arr.into_vec()?;
            let qtype = QuantType::from_i32(qtype_data[0])?;

            // Read shape
            let shape_arr = npz.by_name(&shape_key)?
                .ok_or_else(|| anyhow!("Missing shape for {}", tensor_name))?;
            let shape: Vec<usize> = shape_arr.into_vec::<i64>()?
                .iter()
                .map(|&x| x as usize)
                .collect();

            // Read data based on type
            let data = if qtype == QuantType::F32 {
                // FP32: just read the data array
                let data_key = format!("{}||data", tensor_name);
                let data_arr = npz.by_name(&data_key)?
                    .ok_or_else(|| anyhow!("Missing data for {}", tensor_name))?;
                let f32_data: Vec<f32> = data_arr.into_vec()?;

                // Convert to bytes
                let mut bytes = Vec::with_capacity(f32_data.len() * 4);
                for val in f32_data {
                    bytes.extend_from_slice(&val.to_le_bytes());
                }
                bytes
            } else {
                // Quantized: read scales and qweights
                let scales_key = format!("{}||scales", tensor_name);
                let qweights_key = format!("{}||qweights", tensor_name);

                let scales_arr = npz.by_name(&scales_key)?
                    .ok_or_else(|| anyhow!("Missing scales for {}", tensor_name))?;
                let scales: Vec<f16> = scales_arr.into_vec()?;

                let qweights_arr = npz.by_name(&qweights_key)?
                    .ok_or_else(|| anyhow!("Missing qweights for {}", tensor_name))?;

                let qweights: Vec<u8> = if qtype == QuantType::Q8_0 {
                    // Q8_0: int8 values
                    let i8_weights: Vec<i8> = qweights_arr.into_vec()?;
                    i8_weights.iter().map(|&x| x as u8).collect()
                } else {
                    // Q4_0: packed uint8 values
                    qweights_arr.into_vec()?
                };

                // Pack scales and qweights together
                let mut bytes = Vec::with_capacity(scales.len() * 2 + qweights.len());
                for scale in scales {
                    bytes.extend_from_slice(&scale.to_le_bytes());
                }
                bytes.extend_from_slice(&qweights);
                bytes
            };

            weights.insert(
                tensor_name,
                QuantizedWeight {
                    qtype,
                    shape,
                    data,
                },
            );
        }

        Ok(Self { weights, device })
    }

    /// Get a tensor by name, dequantizing if necessary
    pub fn get(&self, name: &str) -> Result<Tensor> {
        let weight = self
            .weights
            .get(name)
            .ok_or_else(|| anyhow!("Weight not found: {}", name))?;

        match weight.qtype {
            QuantType::F32 => {
                // FP32: directly load
                let num_elements: usize = weight.shape.iter().product();
                let mut f32_data = Vec::with_capacity(num_elements);
                for chunk in weight.data.chunks_exact(4) {
                    let bytes = [chunk[0], chunk[1], chunk[2], chunk[3]];
                    f32_data.push(f32::from_le_bytes(bytes));
                }
                Ok(Tensor::from_vec(f32_data, weight.shape.as_slice(), &self.device)?)
            }
            QuantType::Q8_0 => self.dequantize_q8_0(weight),
            QuantType::Q4_0 => self.dequantize_q4_0(weight),
        }
    }

    /// Dequantize Q8_0 format
    fn dequantize_q8_0(&self, weight: &QuantizedWeight) -> Result<Tensor> {
        const BLOCK_SIZE: usize = 32;
        let num_elements: usize = weight.shape.iter().product();
        let n_blocks = (num_elements + BLOCK_SIZE - 1) / BLOCK_SIZE;

        // Parse scales and qweights from packed data
        let scales_bytes = n_blocks * 2; // float16 = 2 bytes
        let qweights_bytes = n_blocks * BLOCK_SIZE;

        if weight.data.len() < scales_bytes + qweights_bytes {
            return Err(anyhow!("Invalid Q8_0 data length"));
        }

        let scales_data = &weight.data[..scales_bytes];
        let qweights_data = &weight.data[scales_bytes..scales_bytes + qweights_bytes];

        // Parse scales
        let mut scales = Vec::with_capacity(n_blocks);
        for chunk in scales_data.chunks_exact(2) {
            let bytes = [chunk[0], chunk[1]];
            scales.push(f16::from_le_bytes(bytes).to_f32());
        }

        // Dequantize
        let mut dequantized = Vec::with_capacity(num_elements);
        for block_idx in 0..n_blocks {
            let scale = scales[block_idx];
            let qweight_start = block_idx * BLOCK_SIZE;
            let qweight_end = (qweight_start + BLOCK_SIZE).min(qweights_data.len());

            for &qweight_byte in &qweights_data[qweight_start..qweight_end] {
                let qweight = qweight_byte as i8;
                let value = scale * (qweight as f32 / 127.0);
                dequantized.push(value);
                if dequantized.len() >= num_elements {
                    break;
                }
            }
        }

        // Truncate to actual size (remove padding)
        dequantized.truncate(num_elements);

        Ok(Tensor::from_vec(dequantized, weight.shape.as_slice(), &self.device)?)
    }

    /// Dequantize Q4_0 format
    fn dequantize_q4_0(&self, weight: &QuantizedWeight) -> Result<Tensor> {
        const BLOCK_SIZE: usize = 32;
        let num_elements: usize = weight.shape.iter().product();
        let n_blocks = (num_elements + BLOCK_SIZE - 1) / BLOCK_SIZE;

        // Parse scales and qweights from packed data
        let scales_bytes = n_blocks * 2; // float16 = 2 bytes
        let qweights_bytes = n_blocks * 16; // 32 values packed into 16 bytes

        if weight.data.len() < scales_bytes + qweights_bytes {
            return Err(anyhow!("Invalid Q4_0 data length"));
        }

        let scales_data = &weight.data[..scales_bytes];
        let qweights_data = &weight.data[scales_bytes..scales_bytes + qweights_bytes];

        // Parse scales
        let mut scales = Vec::with_capacity(n_blocks);
        for chunk in scales_data.chunks_exact(2) {
            let bytes = [chunk[0], chunk[1]];
            scales.push(f16::from_le_bytes(bytes).to_f32());
        }

        // Dequantize
        let mut dequantized = Vec::with_capacity(num_elements);
        for block_idx in 0..n_blocks {
            let scale = scales[block_idx];
            let qweight_start = block_idx * 16;
            let qweight_end = (qweight_start + 16).min(qweights_data.len());

            // Unpack 4-bit values (2 per byte)
            for &packed_byte in &qweights_data[qweight_start..qweight_end] {
                // Low nibble (first value)
                let qweight1 = (packed_byte & 0xF) as i8 - 8; // Convert back to [-8, 7]
                let value1 = scale * (qweight1 as f32 / 7.0);
                dequantized.push(value1);
                if dequantized.len() >= num_elements {
                    break;
                }

                // High nibble (second value)
                let qweight2 = ((packed_byte >> 4) & 0xF) as i8 - 8;
                let value2 = scale * (qweight2 as f32 / 7.0);
                dequantized.push(value2);
                if dequantized.len() >= num_elements {
                    break;
                }
            }
            if dequantized.len() >= num_elements {
                break;
            }
        }

        // Truncate to actual size (remove padding)
        dequantized.truncate(num_elements);

        Ok(Tensor::from_vec(dequantized, weight.shape.as_slice(), &self.device)?)
    }

    /// Check if a weight exists
    pub fn contains(&self, name: &str) -> bool {
        self.weights.contains_key(name)
    }

    /// Get all weight names
    pub fn weight_names(&self) -> Vec<String> {
        self.weights.keys().cloned().collect()
    }
}
