//! Triton-compiled DXIL kernel dispatch for Moonshine encoder on D3D12.
//!
//! Pre-compiled DXIL bytecode (generated by Triton AOT → HLSL → DXC).
//! All kernels use RWStructuredBuffer<half> for buffer args (SM 6.2+ native half)
//! and cbuffer root constants for scalar args + grid dimensions.

use anyhow::Result;
use candle_d3d12_kernels::{BufferBinding, Gpu, GpuBuffer, ID3D12PipelineState};
use std::sync::Arc;

fn cdiv(a: usize, b: usize) -> usize {
    (a + b - 1) / b
}

// Auto-generated: DXIL constants, TritonD3D12Kernels struct + load(),
// D3D12DecoderKernels struct + load().
include!("../kernels/out/generated/triton_d3d12_gen.rs");

impl TritonD3D12Kernels {

    /// Select the best matmul PSO based on block size and fp16_acc preference.
    fn select_matmul_pso(&self, block_m: usize) -> &ID3D12PipelineState {
        if self.prefer_fp16_acc {
            if let Some(ref pso) = self.matmul_acc16_64x64 {
                return pso;
            }
        }
        if block_m >= 128 {
            self.matmul_128x128.as_ref().unwrap_or(&self.matmul_64x64)
        } else {
            &self.matmul_64x64
        }
    }

    /// Select the best matmul+bias PSO based on fp16_acc preference.
    fn select_matmul_bias_pso(&self) -> &ID3D12PipelineState {
        if self.prefer_fp16_acc {
            if let Some(ref pso) = self.matmul_bias_acc16_32x32 {
                return pso;
            }
        }
        &self.matmul_bias_32x32
    }
}

// ── Helper: pack i32 as u32 root constant ──

fn i32_as_u32(v: i32) -> u32 {
    v as u32
}

// ── Buffer management ──

/// Create a GPU buffer for `count` half-precision elements.
pub fn create_f16_buffer(gpu: &Gpu, count: usize) -> Result<GpuBuffer> {
    let size_bytes = (count * 2) as u64; // half = 2 bytes
    gpu.create_buffer(size_bytes)
        .map_err(|e| anyhow::anyhow!("create_buffer: {e}"))
}

/// Upload F16 data (as raw bytes) to a GPU buffer.
pub fn upload_f16(gpu: &Gpu, data: &[u8], dst: &GpuBuffer) -> Result<()> {
    gpu.upload_to_buffer(data, dst)
        .map_err(|e| anyhow::anyhow!("upload: {e}"))
}

/// Download GPU buffer to F16 bytes.
pub fn download_f16(gpu: &Gpu, src: &GpuBuffer, count: usize) -> Result<Vec<u8>> {
    let size_bytes = (count * 2) as u64;
    gpu.download_buffer(src, size_bytes)
        .map_err(|e| anyhow::anyhow!("download: {e}"))
}

/// Bind a buffer as RWStructuredBuffer<half> UAV.
fn uav_f16<'a>(buf: &'a GpuBuffer, count: u32) -> BufferBinding<'a> {
    BufferBinding::structured_f16(buf, count)
}

/// Bind a buffer as RWStructuredBuffer<float> UAV.
fn uav_f32<'a>(buf: &'a GpuBuffer, count: u32) -> BufferBinding<'a> {
    BufferBinding::structured_f32(buf, count)
}

/// Create a GPU buffer for `count` float32 elements.
pub fn create_f32_buffer(gpu: &Gpu, count: usize) -> Result<GpuBuffer> {
    let size_bytes = (count * 4) as u64;
    gpu.create_buffer(size_bytes)
        .map_err(|e| anyhow::anyhow!("create_f32_buffer: {e}"))
}

/// Upload F32 data (as raw bytes) to a GPU buffer.
pub fn upload_f32(gpu: &Gpu, data: &[u8], dst: &GpuBuffer) -> Result<()> {
    gpu.upload_to_buffer(data, dst)
        .map_err(|e| anyhow::anyhow!("upload_f32: {e}"))
}

/// Download GPU buffer to F32 bytes.
pub fn download_f32(gpu: &Gpu, src: &GpuBuffer, count: usize) -> Result<Vec<u8>> {
    let size_bytes = (count * 4) as u64;
    gpu.download_buffer(src, size_bytes)
        .map_err(|e| anyhow::anyhow!("download_f32: {e}"))
}

// ── Dispatch functions ──

/// Dispatch matmul: C[M,N] = A[M,K] @ B[K,N] (all F16)
///
/// B must be [K, N] row-major (stride_bk=N, stride_bn=1).
/// Automatically selects fp16 or fp32 accumulation based on `prefer_fp16_acc`.
pub fn triton_d3d12_matmul(
    kernels: &TritonD3D12Kernels,
    a: &GpuBuffer,
    b: &GpuBuffer,
    out: &GpuBuffer,
    m: usize,
    n: usize,
    k: usize,
    block_m: usize,
    _block_n: usize,
) -> Result<()> {
    let pso = kernels.select_matmul_pso(block_m);

    // fp16 acc variants always use 64x64 tiles
    let (bm, bn) = if kernels.prefer_fp16_acc && kernels.matmul_acc16_64x64.is_some() {
        (64, 64)
    } else if block_m >= 128 && kernels.matmul_128x128.is_some() {
        (128, 128)
    } else {
        (64, 64)
    };

    let grid_x = cdiv(m, bm) as u32;
    let grid_y = cdiv(n, bn) as u32;

    // cbuffer layout: arg3..arg11 (9 scalars) + grid_dim_x/y/z (3)
    let root_constants: Vec<u32> = vec![
        i32_as_u32(m as i32),         // arg3: M
        i32_as_u32(n as i32),         // arg4: N
        i32_as_u32(k as i32),         // arg5: K
        i32_as_u32(k as i32),         // arg6: stride_am = K
        i32_as_u32(1),                // arg7: stride_ak = 1
        i32_as_u32(n as i32),         // arg8: stride_bk = N
        i32_as_u32(1),                // arg9: stride_bn = 1
        i32_as_u32(n as i32),         // arg10: stride_cm = N
        i32_as_u32(1),                // arg11: stride_cn = 1
        grid_x, grid_y, 1,           // grid dims
    ];

    let uavs = [
        uav_f16(a, (m * k) as u32),
        uav_f16(b, (k * n) as u32),
        uav_f16(out, (m * n) as u32),
    ];

    kernels.gpu.dispatch_uav_only(pso, &root_constants, &uavs, [grid_x, grid_y, 1])
        .map_err(|e| anyhow::anyhow!("matmul dispatch: {e}"))
}

/// Dispatch matmul + bias: C[M,N] = A[M,K] @ B[K,N] + bias[N] (all F16)
/// Automatically selects fp16 or fp32 accumulation based on `prefer_fp16_acc`.
pub fn triton_d3d12_matmul_bias(
    kernels: &TritonD3D12Kernels,
    a: &GpuBuffer,
    b: &GpuBuffer,
    bias: &GpuBuffer,
    out: &GpuBuffer,
    m: usize,
    n: usize,
    k: usize,
    _block_m: usize,
    _block_n: usize,
) -> Result<()> {
    let pso = kernels.select_matmul_bias_pso();
    let bm = 32;
    let bn = 32;

    let grid_x = cdiv(m, bm) as u32;
    let grid_y = cdiv(n, bn) as u32;

    // Pointer args: 0=a, 1=b, 2=bias, 3=c → 4 UAVs
    // Scalar args: 4=M,5=N,6=K,7=stride_am,...12=stride_cn → 9 scalars + 3 grid
    let root_constants: Vec<u32> = vec![
        i32_as_u32(m as i32),
        i32_as_u32(n as i32),
        i32_as_u32(k as i32),
        i32_as_u32(k as i32),         // stride_am = K
        i32_as_u32(1),                // stride_ak = 1
        i32_as_u32(n as i32),         // stride_bk = N
        i32_as_u32(1),                // stride_bn = 1
        i32_as_u32(n as i32),         // stride_cm = N
        i32_as_u32(1),                // stride_cn = 1
        grid_x, grid_y, 1,
    ];

    let uavs = [
        uav_f16(a, (m * k) as u32),
        uav_f16(b, (k * n) as u32),
        uav_f16(bias, n as u32),
        uav_f16(out, (m * n) as u32),
    ];

    kernels.gpu.dispatch_uav_only(pso, &root_constants, &uavs, [grid_x, grid_y, 1])
        .map_err(|e| anyhow::anyhow!("matmul_bias dispatch: {e}"))
}

/// Dispatch unit-offset layernorm: out = LN(x) * (gamma + 1.0) (F16)
///
/// Pointer args: 0=x, 1=gamma, 2=out
/// Scalar args: 3=n_rows, 4=n_cols, 5=stride_x_row, 6=stride_out_row
pub fn triton_d3d12_layernorm(
    kernels: &TritonD3D12Kernels,
    x: &GpuBuffer,
    gamma: &GpuBuffer,
    out: &GpuBuffer,
    n_rows: usize,
    n_cols: usize,
) -> Result<()> {
    let grid_x = n_rows as u32;

    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_rows as i32),
        i32_as_u32(n_cols as i32),
        i32_as_u32(n_cols as i32),     // stride_x_row = n_cols (contiguous)
        i32_as_u32(n_cols as i32),     // stride_out_row = n_cols
        grid_x, 1, 1,
    ];

    let uavs = [
        uav_f16(x, (n_rows * n_cols) as u32),
        uav_f16(gamma, n_cols as u32),
        uav_f16(out, (n_rows * n_cols) as u32),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.layernorm_unit_offset, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("layernorm dispatch: {e}"))
}

/// Dispatch GELU activation: out[i] = gelu(x[i]) (F16)
///
/// Pointer args: 0=x, 1=out
/// Scalar args: 2=n_elements
pub fn triton_d3d12_gelu(
    kernels: &TritonD3D12Kernels,
    x: &GpuBuffer,
    out: &GpuBuffer,
    n_elements: usize,
) -> Result<()> {
    let grid_x = cdiv(n_elements, 1024) as u32;

    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_elements as i32),
        grid_x, 1, 1,
    ];

    let uavs = [
        uav_f16(x, n_elements as u32),
        uav_f16(out, n_elements as u32),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.gelu, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("gelu dispatch: {e}"))
}

/// Dispatch SiLU: out = x * sigmoid(x) (F16)
pub fn triton_d3d12_silu(
    kernels: &TritonD3D12Kernels,
    x: &GpuBuffer,
    out: &GpuBuffer,
    n_elements: usize,
) -> Result<()> {
    let grid_x = cdiv(n_elements, 1024) as u32;

    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_elements as i32),
        grid_x, 1, 1,
    ];

    let uavs = [
        uav_f16(x, n_elements as u32),
        uav_f16(out, n_elements as u32),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.silu, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("silu dispatch: {e}"))
}

/// Dispatch residual add: out = x + residual (F16)
///
/// Pointer args: 0=x, 1=residual, 2=out
/// Scalar args: 3=n_elements
pub fn triton_d3d12_residual_add(
    kernels: &TritonD3D12Kernels,
    x: &GpuBuffer,
    residual: &GpuBuffer,
    out: &GpuBuffer,
    n_elements: usize,
) -> Result<()> {
    let grid_x = cdiv(n_elements, 1024) as u32;

    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_elements as i32),
        grid_x, 1, 1,
    ];

    let uavs = [
        uav_f16(x, n_elements as u32),
        uav_f16(residual, n_elements as u32),
        uav_f16(out, n_elements as u32),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.residual_add, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("residual_add dispatch: {e}"))
}

/// Dispatch mixed-precision matmul: C_f16[M,N] = A_f16[M,K] @ B_f32[K,N]
pub fn triton_d3d12_matmul_f32w(
    kernels: &TritonD3D12Kernels,
    a: &GpuBuffer,    // f16 activation
    b: &GpuBuffer,    // f32 weight
    out: &GpuBuffer,  // f16 output
    m: usize,
    n: usize,
    k: usize,
) -> Result<()> {
    let (bm, bn) = (64, 64);
    let grid_x = cdiv(m, bm) as u32;
    let grid_y = cdiv(n, bn) as u32;

    let root_constants: Vec<u32> = vec![
        i32_as_u32(m as i32),
        i32_as_u32(n as i32),
        i32_as_u32(k as i32),
        i32_as_u32(k as i32),         // stride_am = K
        i32_as_u32(1),                // stride_ak = 1
        i32_as_u32(n as i32),         // stride_bk = N
        i32_as_u32(1),                // stride_bn = 1
        i32_as_u32(n as i32),         // stride_cm = N
        i32_as_u32(1),                // stride_cn = 1
        grid_x, grid_y, 1,
    ];

    let uavs = [
        uav_f16(a, (m * k) as u32),
        uav_f32(b, (k * n) as u32),
        uav_f16(out, (m * n) as u32),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.matmul_f32w_64x64, &root_constants, &uavs, [grid_x, grid_y, 1])
        .map_err(|e| anyhow::anyhow!("matmul_f32w dispatch: {e}"))
}

/// Dispatch mixed-precision matmul+bias: C_f16[M,N] = A_f16[M,K] @ B_f32[K,N] + bias_f32[N]
pub fn triton_d3d12_matmul_bias_f32w(
    kernels: &TritonD3D12Kernels,
    a: &GpuBuffer,     // f16 activation
    b: &GpuBuffer,     // f32 weight
    bias: &GpuBuffer,  // f32 bias
    out: &GpuBuffer,   // f16 output
    m: usize,
    n: usize,
    k: usize,
) -> Result<()> {
    let (bm, bn) = (32, 32);
    let grid_x = cdiv(m, bm) as u32;
    let grid_y = cdiv(n, bn) as u32;

    let root_constants: Vec<u32> = vec![
        i32_as_u32(m as i32),
        i32_as_u32(n as i32),
        i32_as_u32(k as i32),
        i32_as_u32(k as i32),
        i32_as_u32(1),
        i32_as_u32(n as i32),
        i32_as_u32(1),
        i32_as_u32(n as i32),
        i32_as_u32(1),
        grid_x, grid_y, 1,
    ];

    let uavs = [
        uav_f16(a, (m * k) as u32),
        uav_f32(b, (k * n) as u32),
        uav_f32(bias, n as u32),
        uav_f16(out, (m * n) as u32),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.matmul_bias_f32w_32x32, &root_constants, &uavs, [grid_x, grid_y, 1])
        .map_err(|e| anyhow::anyhow!("matmul_bias_f32w dispatch: {e}"))
}

/// Dispatch fused matmul+bias+GELU: C_f16[M,N] = GELU(A_f16[M,K] @ B_f32[K,N] + bias_f32[N])
pub fn triton_d3d12_matmul_bias_gelu_f32w(
    kernels: &TritonD3D12Kernels,
    a: &GpuBuffer,     // f16 activation
    b: &GpuBuffer,     // f32 weight
    bias: &GpuBuffer,  // f32 bias
    out: &GpuBuffer,   // f16 output
    m: usize,
    n: usize,
    k: usize,
) -> Result<()> {
    let (bm, bn) = (32, 32);
    let grid_x = cdiv(m, bm) as u32;
    let grid_y = cdiv(n, bn) as u32;

    let root_constants: Vec<u32> = vec![
        i32_as_u32(m as i32),
        i32_as_u32(n as i32),
        i32_as_u32(k as i32),
        i32_as_u32(k as i32),
        i32_as_u32(1),
        i32_as_u32(n as i32),
        i32_as_u32(1),
        i32_as_u32(n as i32),
        i32_as_u32(1),
        grid_x, grid_y, 1,
    ];

    let uavs = [
        uav_f16(a, (m * k) as u32),
        uav_f32(b, (k * n) as u32),
        uav_f32(bias, n as u32),
        uav_f16(out, (m * n) as u32),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.matmul_bias_gelu_f32w_32x32, &root_constants, &uavs, [grid_x, grid_y, 1])
        .map_err(|e| anyhow::anyhow!("matmul_bias_gelu_f32w dispatch: {e}"))
}

/// Dispatch layernorm with f32 input: out_f16 = LN(x_f32) * (gamma + 1.0)
pub fn triton_d3d12_layernorm_f32in(
    kernels: &TritonD3D12Kernels,
    x: &GpuBuffer,       // f32 input
    gamma: &GpuBuffer,   // f16 gamma
    out: &GpuBuffer,     // f16 output
    n_rows: usize,
    n_cols: usize,
) -> Result<()> {
    let grid_x = n_rows as u32;

    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_rows as i32),
        i32_as_u32(n_cols as i32),
        i32_as_u32(n_cols as i32),     // stride_x_row = n_cols
        i32_as_u32(n_cols as i32),     // stride_out_row = n_cols
        grid_x, 1, 1,
    ];

    let uavs = [
        uav_f32(x, (n_rows * n_cols) as u32),
        uav_f16(gamma, n_cols as u32),
        uav_f16(out, (n_rows * n_cols) as u32),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.layernorm_f32in, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("layernorm_f32in dispatch: {e}"))
}

/// Dispatch mixed-precision residual add: out_f32 = x_f16 + residual_f32
pub fn triton_d3d12_residual_add_f32(
    kernels: &TritonD3D12Kernels,
    x: &GpuBuffer,         // f16 layer output
    residual: &GpuBuffer,  // f32 hidden state
    out: &GpuBuffer,       // f32 output
    n_elements: usize,
) -> Result<()> {
    let grid_x = cdiv(n_elements, 1024) as u32;

    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_elements as i32),
        grid_x, 1, 1,
    ];

    let uavs = [
        uav_f16(x, n_elements as u32),
        uav_f32(residual, n_elements as u32),
        uav_f32(out, n_elements as u32),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.residual_add_f32, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("residual_add_f32 dispatch: {e}"))
}

/// Dispatch f16 → f32 conversion
pub fn triton_d3d12_convert_f16_to_f32(
    kernels: &TritonD3D12Kernels,
    x: &GpuBuffer,     // f16 input
    out: &GpuBuffer,   // f32 output
    n_elements: usize,
) -> Result<()> {
    let grid_x = cdiv(n_elements, 1024) as u32;

    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_elements as i32),
        grid_x, 1, 1,
    ];

    let uavs = [
        uav_f16(x, n_elements as u32),
        uav_f32(out, n_elements as u32),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.convert_f16_to_f32, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("convert_f16_to_f32 dispatch: {e}"))
}

/// Dispatch Flash Attention 2: O = softmax(Q @ K^T / sqrt(d)) @ V
///
/// Q, K, V, O: fp16 buffers with n_heads * seq_len * head_dim elements.
/// stride_h: element stride between heads (head_dim for interleaved, seq_len*head_dim for separated)
/// stride_m: element stride between sequence positions (kv_dim for interleaved, head_dim for separated)
/// Uses online softmax (Dao et al.) with sliding window masking.
/// Grid: (cdiv(seq_len, 32), n_heads, 1)
pub fn triton_d3d12_flash_attention(
    kernels: &TritonD3D12Kernels,
    q: &GpuBuffer,
    k: &GpuBuffer,
    v: &GpuBuffer,
    out: &GpuBuffer,
    n_heads: usize,
    padded_seq: usize,
    seq_len: usize,
    head_dim: usize,
    sm_scale: f32,
    window_left: i32,
    window_right: i32,
) -> Result<()> {
    let bm = 32;
    let grid_x = cdiv(padded_seq, bm) as u32;
    let grid_y = n_heads as u32;

    // Interleaved layout: Q/K/V are [padded_seq, n_heads * head_dim]
    // element(h, s, d) = h * head_dim + s * (n_heads * head_dim) + d
    let stride_h = head_dim as i32;
    let stride_m = (n_heads * head_dim) as i32;

    // cbuffer layout: arg4..arg10 (7 scalars) + grid_dim_x/y/z (3)
    // arg4 = seq_len (for masking), NOT padded_seq
    let stride_o = stride_m; // output has same layout as Q/K/V for encoder
    let root_constants: Vec<u32> = vec![
        i32_as_u32(seq_len as i32),       // arg4: seq_len (mask bound)
        i32_as_u32(stride_h),             // arg5: stride_h
        i32_as_u32(stride_m),             // arg6: stride_qkv
        i32_as_u32(stride_o),             // arg7: stride_o
        sm_scale.to_bits(),               // arg8: sm_scale (as float bits)
        i32_as_u32(window_left),          // arg9: window_left
        i32_as_u32(window_right),         // arg10: window_right
        grid_x, grid_y, 1,               // grid dims
    ];

    let n_elem = (n_heads * padded_seq * head_dim) as u32;
    let uavs = [
        uav_f16(q, n_elem),
        uav_f16(k, n_elem),
        uav_f16(v, n_elem),
        uav_f16(out, n_elem),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.flash_attn_d64, &root_constants, &uavs, [grid_x, grid_y, 1])
        .map_err(|e| anyhow::anyhow!("flash_attention dispatch: {e}"))
}

/// Dispatch softmax over rows: out[r,:] = softmax(x[r,:]) (F16)
///
/// Pointer args: 0=input, 1=output
/// Scalar args: 2=n_rows, 3=n_cols, 4=stride_row
pub fn triton_d3d12_softmax(
    kernels: &TritonD3D12Kernels,
    input: &GpuBuffer,
    output: &GpuBuffer,
    n_rows: usize,
    n_cols: usize,
) -> Result<()> {
    let grid_x = n_rows as u32;

    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_rows as i32),
        i32_as_u32(n_cols as i32),
        i32_as_u32(n_cols as i32),     // stride_row = n_cols (contiguous)
        grid_x, 1, 1,
    ];

    let uavs = [
        uav_f16(input, (n_rows * n_cols) as u32),
        uav_f16(output, (n_rows * n_cols) as u32),
    ];

    kernels.gpu.dispatch_uav_only(&kernels.softmax, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("softmax dispatch: {e}"))
}
