//! Triton-compiled Metal kernel dispatch for Moonshine encoder.
//!
//! Loads pre-compiled .metal source files (generated by Triton AOT compiler),
//! compiles them into Metal compute pipelines, and provides dispatch functions
//! for each kernel type.

use anyhow::Result;
use candle_core::{DType, MetalDevice, MetalStorage, Shape, Storage, Tensor};
use candle_metal_kernels::metal::ComputePipeline;
use objc2_metal::MTLSize;
use std::path::{Path, PathBuf};

fn cdiv(a: usize, b: usize) -> usize {
    (a + b - 1) / b
}

/// All compiled Triton kernel pipelines for the Moonshine encoder.
pub struct TritonKernels {
    pub matmul_64x64: ComputePipeline,
    pub matmul_bias_32x32: ComputePipeline,
    pub matmul_bias_gelu_32x32: ComputePipeline,
    pub layernorm_unit_offset: ComputePipeline,
    pub residual_add: ComputePipeline,
    pub flash_attention: ComputePipeline,
}

impl TritonKernels {
    /// Load kernels from .metal source files in the given directory.
    pub fn load(metal_device: &MetalDevice, kernel_dir: &Path) -> Result<Self> {
        let device = metal_device.device();

        let load = |name: &str, func_name: &str| -> Result<ComputePipeline> {
            let path = kernel_dir.join(format!("{name}.metal"));
            let source = std::fs::read_to_string(&path)
                .map_err(|e| anyhow::anyhow!("Failed to read {}: {e}", path.display()))?;
            let lib = device
                .new_library_with_source(&source, None)
                .map_err(|e| anyhow::anyhow!("Failed to compile {name}: {e}"))?;
            let func = lib
                .get_function(func_name, None)
                .map_err(|e| anyhow::anyhow!("Function {func_name} not found in {name}: {e}"))?;
            let pipeline = device
                .new_compute_pipeline_state_with_function(&func)
                .map_err(|e| anyhow::anyhow!("Pipeline failed for {name}: {e}"))?;
            Ok(pipeline)
        };

        Ok(Self {
            matmul_64x64: load("matmul_fp16_64x64x32", "matmul_fp16")?,
            matmul_bias_32x32: load("matmul_bias_fp16_32x32x32", "matmul_bias_fp16")?,
            matmul_bias_gelu_32x32: load("matmul_bias_gelu_fp16_32x32x32", "matmul_bias_gelu_fp16")?,
            layernorm_unit_offset: load("layernorm_unit_offset_768", "layernorm_unit_offset")?,
            residual_add: load("residual_add_fp16", "residual_add")?,
            flash_attention: load("flash_attention_fwd_32x32x64", "flash_attention_fwd")?,
        })
    }
}

/// Create an empty F16 output tensor on the Metal device.
pub fn empty_f16(device: &MetalDevice, shape: impl Into<Shape>) -> Result<Tensor> {
    let shape: Shape = shape.into();
    let n = shape.elem_count();
    let buffer = device.new_buffer(n, DType::F16, "triton_out")?;
    let storage = MetalStorage::new(buffer, device.clone(), n, DType::F16);
    Ok(Tensor::from_storage(
        Storage::Metal(storage),
        shape,
        candle_core::op::BackpropOp::none(),
        false,
    ))
}

/// Helper: extract MetalStorage from a tensor. Panics on non-Metal tensor.
macro_rules! with_metal_buffers {
    // 3 tensors + output
    ($a:expr, $b:expr, $c:expr, $out:expr, |$a_buf:ident, $a_off:ident, $b_buf:ident, $b_off:ident, $c_buf:ident, $c_off:ident, $o_buf:ident, $o_off:ident| $body:block) => {{
        let (sa, la) = $a.storage_and_layout();
        let (sb, lb) = $b.storage_and_layout();
        let (sc, lc) = $c.storage_and_layout();
        let (so, lo) = $out.storage_and_layout();
        let $a_off = la.start_offset() * $a.dtype().size_in_bytes();
        let $b_off = lb.start_offset() * $b.dtype().size_in_bytes();
        let $c_off = lc.start_offset() * $c.dtype().size_in_bytes();
        let $o_off = lo.start_offset() * $out.dtype().size_in_bytes();
        match (&*sa, &*sb, &*sc, &*so) {
            (Storage::Metal(ma), Storage::Metal(mb), Storage::Metal(mc), Storage::Metal(mo)) => {
                let $a_buf = ma.buffer();
                let $b_buf = mb.buffer();
                let $c_buf = mc.buffer();
                let $o_buf = mo.buffer();
                $body
            }
            _ => anyhow::bail!("All tensors must be on Metal device"),
        }
    }};
    // 2 tensors + output
    ($a:expr, $b:expr, $out:expr, |$a_buf:ident, $a_off:ident, $b_buf:ident, $b_off:ident, $o_buf:ident, $o_off:ident| $body:block) => {{
        let (sa, la) = $a.storage_and_layout();
        let (sb, lb) = $b.storage_and_layout();
        let (so, lo) = $out.storage_and_layout();
        let $a_off = la.start_offset() * $a.dtype().size_in_bytes();
        let $b_off = lb.start_offset() * $b.dtype().size_in_bytes();
        let $o_off = lo.start_offset() * $out.dtype().size_in_bytes();
        match (&*sa, &*sb, &*so) {
            (Storage::Metal(ma), Storage::Metal(mb), Storage::Metal(mo)) => {
                let $a_buf = ma.buffer();
                let $b_buf = mb.buffer();
                let $o_buf = mo.buffer();
                $body
            }
            _ => anyhow::bail!("All tensors must be on Metal device"),
        }
    }};
}

// ── Dispatch functions ──────────────────────────────────────────────────────

/// Dispatch matmul: C[M,N] = A[M,K] @ B[K,N]
///
/// B must be stored as [K, N] row-major (stride_bk=N, stride_bn=1).
/// The kernel's vec4 cooperative load requires the N dimension to be contiguous.
///
/// For weight matrices stored as [N, K] (e.g., from GGUF), transpose before calling:
///   `weight.t()?.contiguous()?`
pub fn triton_matmul(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    a: &Tensor,
    b: &Tensor,
    m: usize,
    n: usize,
    k: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (m, n))?;

    with_metal_buffers!(a, b, &out, |a_buf, a_off, b_buf, b_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(a_buf), a_off);
        encoder.set_buffer(1, Some(b_buf), b_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(m as i32));
        encoder.set_bytes(4, &(n as i32));
        encoder.set_bytes(5, &(k as i32));
        encoder.set_bytes(6, &(k as i32));      // stride_am = K
        encoder.set_bytes(7, &1i32);            // stride_ak = 1
        encoder.set_bytes(8, &(n as i32));      // stride_bk = N (B=[K,N], row-major)
        encoder.set_bytes(9, &1i32);            // stride_bn = 1
        encoder.set_bytes(10, &(n as i32));     // stride_cm = N
        encoder.set_bytes(11, &1i32);           // stride_cn = 1

        let grid = MTLSize {
            width: cdiv(m, 64) as usize,
            height: cdiv(n, 64) as usize,
            depth: 1,
        };
        let tg = MTLSize { width: 1024, height: 1, depth: 1 };
        encoder.dispatch_thread_groups(grid, tg);
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch matmul + bias: C[M,N] = A[M,K] @ B[K,N] + bias[N]
///
/// B must be [K, N] row-major. Transpose weights before calling.
/// `block_m`/`block_n` must match the compiled kernel tile size.
pub fn triton_matmul_bias(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    a: &Tensor,
    b: &Tensor,
    bias: &Tensor,
    m: usize,
    n: usize,
    k: usize,
    block_m: usize,
    block_n: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (m, n))?;

    with_metal_buffers!(a, b, bias, &out, |a_buf, a_off, b_buf, b_off, bias_buf, bias_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(a_buf), a_off);
        encoder.set_buffer(1, Some(b_buf), b_off);
        encoder.set_buffer(2, Some(bias_buf), bias_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(m as i32));
        encoder.set_bytes(5, &(n as i32));
        encoder.set_bytes(6, &(k as i32));
        encoder.set_bytes(7, &(k as i32));      // stride_am = K
        encoder.set_bytes(8, &1i32);            // stride_ak = 1
        encoder.set_bytes(9, &(n as i32));      // stride_bk = N (B=[K,N])
        encoder.set_bytes(10, &1i32);           // stride_bn = 1
        encoder.set_bytes(11, &(n as i32));     // stride_cm = N
        encoder.set_bytes(12, &1i32);           // stride_cn = 1

        let grid = MTLSize {
            width: cdiv(m, block_m),
            height: cdiv(n, block_n),
            depth: 1,
        };
        let tg = MTLSize { width: 1024, height: 1, depth: 1 };
        encoder.dispatch_thread_groups(grid, tg);
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch fused matmul + bias + GELU: C[M,N] = GELU(A[M,K] @ B[K,N] + bias[N])
///
/// B must be [K, N] row-major. Transpose weights before calling.
/// `block_m`/`block_n` must match the compiled kernel tile size.
pub fn triton_matmul_bias_gelu(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    a: &Tensor,
    b: &Tensor,
    bias: &Tensor,
    m: usize,
    n: usize,
    k: usize,
    block_m: usize,
    block_n: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (m, n))?;

    with_metal_buffers!(a, b, bias, &out, |a_buf, a_off, b_buf, b_off, bias_buf, bias_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(a_buf), a_off);
        encoder.set_buffer(1, Some(b_buf), b_off);
        encoder.set_buffer(2, Some(bias_buf), bias_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(m as i32));
        encoder.set_bytes(5, &(n as i32));
        encoder.set_bytes(6, &(k as i32));
        encoder.set_bytes(7, &(k as i32));      // stride_am = K
        encoder.set_bytes(8, &1i32);            // stride_ak = 1
        encoder.set_bytes(9, &(n as i32));      // stride_bk = N (B=[K,N])
        encoder.set_bytes(10, &1i32);           // stride_bn = 1
        encoder.set_bytes(11, &(n as i32));     // stride_cm = N
        encoder.set_bytes(12, &1i32);           // stride_cn = 1

        let grid = MTLSize {
            width: cdiv(m, block_m),
            height: cdiv(n, block_n),
            depth: 1,
        };
        let tg = MTLSize { width: 1024, height: 1, depth: 1 };
        encoder.dispatch_thread_groups(grid, tg);
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch unit-offset layernorm: out = LN(x) * (gamma + 1.0)
pub fn triton_layernorm_unit_offset(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    gamma: &Tensor,
    n_rows: usize,
    n_cols: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (n_rows, n_cols))?;

    with_metal_buffers!(x, gamma, &out, |x_buf, x_off, g_buf, g_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(g_buf), g_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_rows as i32));
        encoder.set_bytes(4, &(n_cols as i32));
        encoder.set_bytes(5, &(n_cols as i32));
        encoder.set_bytes(6, &(n_cols as i32));

        let grid = MTLSize { width: n_rows as usize, height: 1, depth: 1 };
        let tg = MTLSize { width: 1024, height: 1, depth: 1 };
        encoder.dispatch_thread_groups(grid, tg);
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch residual add: out = x + residual (element-wise F16)
pub fn triton_residual_add(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    residual: &Tensor,
    n_elements: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, x.shape())?;

    with_metal_buffers!(x, residual, &out, |x_buf, x_off, r_buf, r_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(r_buf), r_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_elements as i32));

        let grid = MTLSize { width: cdiv(n_elements, 1024) as usize, height: 1, depth: 1 };
        let tg = MTLSize { width: 1024, height: 1, depth: 1 };
        encoder.dispatch_thread_groups(grid, tg);
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch Flash Attention 2 with sliding window.
///
/// Q, K, V, O: contiguous buffers with same strides.
/// stride_h: offset (in elements) between consecutive heads.
/// stride_m: offset (in elements) between consecutive rows within a head.
/// head_dim must be contiguous (stride 1).
///
/// Common layouts:
///   [n_heads, seq_len, D]: stride_h = seq_len * D, stride_m = D
///   [seq_len, n_heads, D]: stride_h = D, stride_m = n_heads * D
///
/// The kernel fuses QK^T, softmax with sliding window masking, and attn*V
/// in a single pass using online softmax (no materialised seq×seq matrix).
pub fn triton_flash_attention(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    q: &Tensor,
    k: &Tensor,
    v: &Tensor,
    out: &Tensor,
    n_heads: usize,
    seq_len: usize,
    head_dim: usize,
    stride_h: i32,
    stride_m: i32,
    sm_scale: f32,
    window_left: i32,
    window_right: i32,
) -> Result<()> {
    with_metal_buffers!(q, k, v, out, |q_buf, q_off, k_buf, k_off, v_buf, v_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(q_buf), q_off);
        encoder.set_buffer(1, Some(k_buf), k_off);
        encoder.set_buffer(2, Some(v_buf), v_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(seq_len as i32));
        encoder.set_bytes(5, &stride_h);
        encoder.set_bytes(6, &stride_m);
        encoder.set_bytes(7, &sm_scale);
        encoder.set_bytes(8, &window_left);
        encoder.set_bytes(9, &window_right);

        let grid = MTLSize {
            width: cdiv(seq_len, 32),
            height: n_heads,
            depth: 1,
        };
        let tg = MTLSize { width: 832, height: 1, depth: 1 };
        encoder.dispatch_thread_groups(grid, tg);
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(())
}

/// Default kernel directory.
pub fn default_kernel_dir() -> PathBuf {
    let triton_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("triton/third_party/metal/moonshine_metal");
    if triton_dir.exists() {
        return triton_dir;
    }
    PathBuf::from("moonshine_metal")
}
