//! Triton-compiled Metal kernel dispatch for Moonshine encoder.
//!
//! Both Apple Silicon and Intel: loads pre-compiled .metallib binaries (zero runtime compilation).
//! Apple metallibs use Metal 3.1 (simdgroup), Intel metallibs use Metal 2.4 (scalar).
//! All generated by kernels/build.py + ninja, compiled via xcrun metal.

use anyhow::Result;
use candle_core::{DType, MetalDevice, MetalStorage, Shape, Storage, Tensor};
use candle_metal_kernels::metal::{Buffer, ComputePipeline};
use objc2_metal::MTLSize;
use std::sync::Arc;

// Auto-generated: kernel_data module, TritonKernels struct + load(),
// DecoderKernels struct + load().
include!("../kernels/out/generated/triton_metal_gen.rs");

// ── GpuBuffer: lightweight GPU buffer wrapper (same name on Metal + D3D12) ──

/// A Metal GPU buffer with byte offset. Same name as D3D12's GpuBuffer
/// to maximize code-sharing potential between platforms.
pub struct GpuBuffer {
    buffer: Arc<Buffer>,
    pub offset: usize, // byte offset into buffer
}

impl GpuBuffer {
    /// Allocate an uninitialized F16 buffer.
    pub fn alloc_f16(device: &MetalDevice, count: usize) -> Result<Self> {
        let buffer = device.new_buffer(count, DType::F16, "mb_f16")?;
        Ok(Self { buffer, offset: 0 })
    }

    /// Allocate an uninitialized F32 buffer.
    pub fn alloc_f32(device: &MetalDevice, count: usize) -> Result<Self> {
        let buffer = device.new_buffer(count, DType::F32, "mb_f32")?;
        Ok(Self { buffer, offset: 0 })
    }

    /// Create from F16 data (upload to GPU).
    pub fn from_f16_data(device: &MetalDevice, data: &[half::f16]) -> Result<Self> {
        let buffer = device.new_buffer_with_data(data)?;
        Ok(Self { buffer, offset: 0 })
    }

    /// Create from F32 data (upload to GPU).
    pub fn from_f32_data(device: &MetalDevice, data: &[f32]) -> Result<Self> {
        let buffer = device.new_buffer_with_data(data)?;
        Ok(Self { buffer, offset: 0 })
    }

    /// Get the underlying Metal buffer for dispatch.
    #[inline]
    pub fn buf(&self) -> &Buffer { &self.buffer }

    /// Raw pointer to buffer contents (for CPU read/write on shared buffers).
    #[inline]
    pub fn contents_ptr(&self) -> *mut u8 {
        unsafe { self.buffer.contents().add(self.offset) }
    }

    /// Create a view into this buffer at a byte offset.
    #[inline]
    pub fn with_offset(&self, byte_offset: usize) -> Self {
        Self {
            buffer: self.buffer.clone(),
            offset: self.offset + byte_offset,
        }
    }
}

fn cdiv(a: usize, b: usize) -> usize {
    (a + b - 1) / b
}

/// Set dynamic threadgroup memory for AIR kernels.
/// AIR kernels declare threadgroup memory as a function parameter (ptr addrspace(3)),
/// unlike MSL which uses static `threadgroup` declarations. This must be called before
/// dispatch for any AIR kernel that uses shared memory. Safe to call for MSL too (no-op).
#[cfg(target_arch = "aarch64")]
fn set_air_tg_mem(encoder: &candle_metal_kernels::metal::ComputeCommandEncoder, bytes: usize) {
    if bytes > 0 {
        encoder.set_threadgroup_memory_length(0, bytes);
    }
}

/// Determine threadgroup size for dispatch.
/// Clamps to the pipeline's max (critical for Intel GPUs with < 1024 limit).
fn tg_size(pipeline: &ComputePipeline, requested: usize) -> MTLSize {
    let max = pipeline.max_total_threads_per_threadgroup();
    MTLSize { width: requested.min(max), height: 1, depth: 1 }
}

/// Threadgroup size for matmul kernels.
/// On aarch64: 32x32 uses AIR (bs=128), larger tiles use MSL (simdgroup_matrix, 1024 threads).
#[cfg(target_arch = "aarch64")]
fn matmul_tg_size(pipeline: &ComputePipeline, block_m: usize, _block_n: usize) -> MTLSize {
    if block_m <= 32 { tg_size(pipeline, 128) } else { tg_size(pipeline, 1024) }
}
#[cfg(not(target_arch = "aarch64"))]
fn matmul_tg_size(pipeline: &ComputePipeline, _block_m: usize, _block_n: usize) -> MTLSize {
    tg_size(pipeline, 1024)
}

/// Threadgroup size for flash attention (MSL kernel uses 832 threads).
fn fa_tg_size(pipeline: &ComputePipeline) -> MTLSize {
    tg_size(pipeline, 832)
}

// TritonKernels struct + load() are auto-generated above via include!.
// DecoderKernels struct + load() are also auto-generated.

/// Create an empty F16 output tensor on the Metal device.
pub fn empty_f16(device: &MetalDevice, shape: impl Into<Shape>) -> Result<Tensor> {
    let shape: Shape = shape.into();
    let n = shape.elem_count();
    let buffer = device.new_buffer(n, DType::F16, "triton_out")?;
    let storage = MetalStorage::new(buffer, device.clone(), n, DType::F16);
    Ok(Tensor::from_storage(
        Storage::Metal(storage),
        shape,
        candle_core::op::BackpropOp::none(),
        false,
    ))
}

/// Helper: extract MetalStorage from a tensor. Panics on non-Metal tensor.
macro_rules! with_metal_buffers {
    // 3 tensors + output
    ($a:expr, $b:expr, $c:expr, $out:expr, |$a_buf:ident, $a_off:ident, $b_buf:ident, $b_off:ident, $c_buf:ident, $c_off:ident, $o_buf:ident, $o_off:ident| $body:block) => {{
        let (sa, la) = $a.storage_and_layout();
        let (sb, lb) = $b.storage_and_layout();
        let (sc, lc) = $c.storage_and_layout();
        let (so, lo) = $out.storage_and_layout();
        let $a_off = la.start_offset() * $a.dtype().size_in_bytes();
        let $b_off = lb.start_offset() * $b.dtype().size_in_bytes();
        let $c_off = lc.start_offset() * $c.dtype().size_in_bytes();
        let $o_off = lo.start_offset() * $out.dtype().size_in_bytes();
        match (&*sa, &*sb, &*sc, &*so) {
            (Storage::Metal(ma), Storage::Metal(mb), Storage::Metal(mc), Storage::Metal(mo)) => {
                let $a_buf = ma.buffer();
                let $b_buf = mb.buffer();
                let $c_buf = mc.buffer();
                let $o_buf = mo.buffer();
                $body
            }
            _ => anyhow::bail!("All tensors must be on Metal device"),
        }
    }};
    // 2 tensors + output
    ($a:expr, $b:expr, $out:expr, |$a_buf:ident, $a_off:ident, $b_buf:ident, $b_off:ident, $o_buf:ident, $o_off:ident| $body:block) => {{
        let (sa, la) = $a.storage_and_layout();
        let (sb, lb) = $b.storage_and_layout();
        let (so, lo) = $out.storage_and_layout();
        let $a_off = la.start_offset() * $a.dtype().size_in_bytes();
        let $b_off = lb.start_offset() * $b.dtype().size_in_bytes();
        let $o_off = lo.start_offset() * $out.dtype().size_in_bytes();
        match (&*sa, &*sb, &*so) {
            (Storage::Metal(ma), Storage::Metal(mb), Storage::Metal(mo)) => {
                let $a_buf = ma.buffer();
                let $b_buf = mb.buffer();
                let $o_buf = mo.buffer();
                $body
            }
            _ => anyhow::bail!("All tensors must be on Metal device"),
        }
    }};
}

// ── Dispatch functions ──────────────────────────────────────────────────────

/// Dispatch matmul: C[M,N] = A[M,K] @ B[K,N]
///
/// B must be stored as [K, N] row-major (stride_bk=N, stride_bn=1).
/// The kernel's vec4 cooperative load requires the N dimension to be contiguous.
///
/// For weight matrices stored as [N, K] (e.g., from GGUF), transpose before calling:
///   `weight.t()?.contiguous()?`
pub fn triton_matmul(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    a: &Tensor,
    b: &Tensor,
    m: usize,
    n: usize,
    k: usize,
    block_m: usize,
    block_n: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (m, n))?;

    with_metal_buffers!(a, b, &out, |a_buf, a_off, b_buf, b_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(a_buf), a_off);
        encoder.set_buffer(1, Some(b_buf), b_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(m as i32));
        encoder.set_bytes(4, &(n as i32));
        encoder.set_bytes(5, &(k as i32));
        encoder.set_bytes(6, &(k as i32));      // stride_am = K
        encoder.set_bytes(7, &1i32);            // stride_ak = 1
        encoder.set_bytes(8, &(n as i32));      // stride_bk = N (B=[K,N], row-major)
        encoder.set_bytes(9, &1i32);            // stride_bn = 1
        encoder.set_bytes(10, &(n as i32));     // stride_cm = N
        encoder.set_bytes(11, &1i32);           // stride_cn = 1

        let grid = MTLSize {
            width: cdiv(m, block_m),
            height: cdiv(n, block_n),
            depth: 1,
        };
        #[cfg(target_arch = "aarch64")]
        if block_m <= 32 { set_air_tg_mem(&encoder, 4096); }
        encoder.dispatch_thread_groups(grid, matmul_tg_size(pipeline, block_m, block_n));
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch matmul + bias: C[M,N] = A[M,K] @ B[K,N] + bias[N]
///
/// B must be [K, N] row-major. Transpose weights before calling.
/// `block_m`/`block_n` must match the compiled kernel tile size.
pub fn triton_matmul_bias(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    a: &Tensor,
    b: &Tensor,
    bias: &Tensor,
    m: usize,
    n: usize,
    k: usize,
    block_m: usize,
    block_n: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (m, n))?;

    with_metal_buffers!(a, b, bias, &out, |a_buf, a_off, b_buf, b_off, bias_buf, bias_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(a_buf), a_off);
        encoder.set_buffer(1, Some(b_buf), b_off);
        encoder.set_buffer(2, Some(bias_buf), bias_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(m as i32));
        encoder.set_bytes(5, &(n as i32));
        encoder.set_bytes(6, &(k as i32));
        encoder.set_bytes(7, &(k as i32));      // stride_am = K
        encoder.set_bytes(8, &1i32);            // stride_ak = 1
        encoder.set_bytes(9, &(n as i32));      // stride_bk = N (B=[K,N])
        encoder.set_bytes(10, &1i32);           // stride_bn = 1
        encoder.set_bytes(11, &(n as i32));     // stride_cm = N
        encoder.set_bytes(12, &1i32);           // stride_cn = 1

        let grid = MTLSize {
            width: cdiv(m, block_m),
            height: cdiv(n, block_n),
            depth: 1,
        };
        #[cfg(target_arch = "aarch64")]
        if block_m <= 32 { set_air_tg_mem(&encoder, 4096); }
        encoder.dispatch_thread_groups(grid, matmul_tg_size(pipeline, block_m, block_n));
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch fused matmul + bias + GELU: C[M,N] = GELU(A[M,K] @ B[K,N] + bias[N])
///
/// B must be [K, N] row-major. Transpose weights before calling.
/// `block_m`/`block_n` must match the compiled kernel tile size.
pub fn triton_matmul_bias_gelu(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    a: &Tensor,
    b: &Tensor,
    bias: &Tensor,
    m: usize,
    n: usize,
    k: usize,
    block_m: usize,
    block_n: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (m, n))?;

    with_metal_buffers!(a, b, bias, &out, |a_buf, a_off, b_buf, b_off, bias_buf, bias_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(a_buf), a_off);
        encoder.set_buffer(1, Some(b_buf), b_off);
        encoder.set_buffer(2, Some(bias_buf), bias_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(m as i32));
        encoder.set_bytes(5, &(n as i32));
        encoder.set_bytes(6, &(k as i32));
        encoder.set_bytes(7, &(k as i32));      // stride_am = K
        encoder.set_bytes(8, &1i32);            // stride_ak = 1
        encoder.set_bytes(9, &(n as i32));      // stride_bk = N (B=[K,N])
        encoder.set_bytes(10, &1i32);           // stride_bn = 1
        encoder.set_bytes(11, &(n as i32));     // stride_cm = N
        encoder.set_bytes(12, &1i32);           // stride_cn = 1

        let grid = MTLSize {
            width: cdiv(m, block_m),
            height: cdiv(n, block_n),
            depth: 1,
        };
        #[cfg(target_arch = "aarch64")]
        if block_m <= 32 { set_air_tg_mem(&encoder, 4096); }
        encoder.dispatch_thread_groups(grid, matmul_tg_size(pipeline, block_m, block_n));
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch unit-offset layernorm: out = LN(x) * (gamma + 1.0)
pub fn triton_layernorm_unit_offset(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    gamma: &Tensor,
    n_rows: usize,
    n_cols: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (n_rows, n_cols))?;

    with_metal_buffers!(x, gamma, &out, |x_buf, x_off, g_buf, g_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(g_buf), g_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_rows as i32));
        encoder.set_bytes(4, &(n_cols as i32));
        encoder.set_bytes(5, &(n_cols as i32));
        encoder.set_bytes(6, &(n_cols as i32));

        let grid = MTLSize { width: n_rows as usize, height: 1, depth: 1 };
        #[cfg(target_arch = "aarch64")]
        set_air_tg_mem(&encoder, 4096);
        encoder.dispatch_thread_groups(grid, tg_size(pipeline, n_cols));
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch bare layernorm: out = (x - mean) / sqrt(var + eps)
/// No gamma scaling — gamma is baked into downstream weights.
pub fn triton_layernorm_bare(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    n_rows: usize,
    n_cols: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (n_rows, n_cols))?;

    {
        let (sx, lx) = x.storage_and_layout();
        let (so, lo) = out.storage_and_layout();
        let x_off = lx.start_offset() * x.dtype().size_in_bytes();
        let o_off = lo.start_offset() * out.dtype().size_in_bytes();
        match (&*sx, &*so) {
            (Storage::Metal(mx), Storage::Metal(mo)) => {
                let encoder = device.command_encoder()?;
                encoder.set_compute_pipeline_state(pipeline);
                encoder.set_buffer(0, Some(mx.buffer()), x_off);
                encoder.set_buffer(1, Some(mo.buffer()), o_off);
                encoder.set_bytes(2, &(n_rows as i32));
                encoder.set_bytes(3, &(n_cols as i32));
                encoder.set_bytes(4, &(n_cols as i32));
                encoder.set_bytes(5, &(n_cols as i32));

                let grid = MTLSize { width: n_rows, height: 1, depth: 1 };
                #[cfg(target_arch = "aarch64")]
                set_air_tg_mem(&encoder, 4096);
                encoder.dispatch_thread_groups(grid, tg_size(pipeline, n_cols));
            }
            _ => anyhow::bail!("Tensors must be on Metal device"),
        }
    }

    Ok(out)
}

/// Dispatch residual add: out = x + residual (element-wise F16)
pub fn triton_residual_add(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    residual: &Tensor,
    n_elements: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, x.shape())?;

    with_metal_buffers!(x, residual, &out, |x_buf, x_off, r_buf, r_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(r_buf), r_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_elements as i32));

        let tg_w = tg_size(pipeline, 1024).width;
        let grid = MTLSize { width: cdiv(n_elements, tg_w) as usize, height: 1, depth: 1 };
        encoder.dispatch_thread_groups(grid, MTLSize { width: tg_w, height: 1, depth: 1 });
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch GELU activation: out[i] = gelu(x[i]) (element-wise F16)
///
/// The kernel processes 1024 elements per threadgroup.
pub fn triton_gelu(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    n_elements: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, x.shape())?;

    {
        let (sx, lx) = x.storage_and_layout();
        let (so, lo) = out.storage_and_layout();
        let x_off = lx.start_offset() * x.dtype().size_in_bytes();
        let o_off = lo.start_offset() * out.dtype().size_in_bytes();
        match (&*sx, &*so) {
            (Storage::Metal(mx), Storage::Metal(mo)) => {
                let encoder = device.command_encoder()?;
                encoder.set_compute_pipeline_state(pipeline);
                encoder.set_buffer(0, Some(mx.buffer()), x_off);
                encoder.set_buffer(1, Some(mo.buffer()), o_off);
                encoder.set_bytes(2, &(n_elements as i32));

                // Kernel hardcodes BLOCK_SIZE=1024
                let grid = MTLSize { width: cdiv(n_elements, 1024), height: 1, depth: 1 };
                encoder.dispatch_thread_groups(grid, tg_size(pipeline, 1024));
            }
            _ => anyhow::bail!("Tensors must be on Metal device"),
        }
    }

    Ok(out)
}

/// Dispatch bias add: out[i] = x[i] + bias[i % n_cols] (element-wise F16)
pub fn triton_bias_add(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    bias: &Tensor,
    n_elements: usize,
    n_cols: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, x.shape())?;

    with_metal_buffers!(x, bias, &out, |x_buf, x_off, b_buf, b_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(b_buf), b_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_elements as i32));
        encoder.set_bytes(4, &(n_cols as i32));

        let tg_w = tg_size(pipeline, 1024).width;
        let grid = MTLSize { width: cdiv(n_elements, tg_w), height: 1, depth: 1 };
        encoder.dispatch_thread_groups(grid, MTLSize { width: tg_w, height: 1, depth: 1 });
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch Flash Attention 2 with sliding window.
///
/// Q, K, V, O: contiguous buffers with same strides.
/// stride_h: offset (in elements) between consecutive heads.
/// stride_m: offset (in elements) between consecutive rows within a head.
/// head_dim must be contiguous (stride 1).
///
/// Common layouts:
///   [n_heads, seq_len, D]: stride_h = seq_len * D, stride_m = D
///   [seq_len, n_heads, D]: stride_h = D, stride_m = n_heads * D
///
/// The kernel fuses QK^T, softmax with sliding window masking, and attn*V
/// in a single pass using online softmax (no materialised seq×seq matrix).
pub fn triton_flash_attention(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    q: &Tensor,
    k: &Tensor,
    v: &Tensor,
    out: &Tensor,
    n_heads: usize,
    seq_len: usize,
    _head_dim: usize,
    stride_h: i32,
    stride_qkv: i32,
    stride_o: i32,
    sm_scale: f32,
    window_left: i32,
    window_right: i32,
) -> Result<()> {
    with_metal_buffers!(q, k, v, out, |q_buf, q_off, k_buf, k_off, v_buf, v_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(q_buf), q_off);
        encoder.set_buffer(1, Some(k_buf), k_off);
        encoder.set_buffer(2, Some(v_buf), v_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(seq_len as i32));
        encoder.set_bytes(5, &stride_h);
        encoder.set_bytes(6, &stride_qkv);
        encoder.set_bytes(7, &stride_o);
        encoder.set_bytes(8, &sm_scale);
        encoder.set_bytes(9, &window_left);
        encoder.set_bytes(10, &window_right);

        // AIR kernels need dynamic threadgroup memory (MSL declares it statically)
        #[cfg(target_arch = "aarch64")]
        encoder.set_threadgroup_memory_length(0, 8192); // FA: 8KB shared memory

        let grid = MTLSize {
            width: cdiv(seq_len, 32),
            height: n_heads,
            depth: 1,
        };
        encoder.dispatch_thread_groups(grid, fa_tg_size(pipeline));
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(())
}

/// Create an empty F32 output tensor on the Metal device.
pub fn empty_f32(device: &MetalDevice, shape: impl Into<Shape>) -> Result<Tensor> {
    let shape: Shape = shape.into();
    let n = shape.elem_count();
    let buffer = device.new_buffer(n, DType::F32, "triton_f32_out")?;
    let storage = MetalStorage::new(buffer, device.clone(), n, DType::F32);
    Ok(Tensor::from_storage(
        Storage::Metal(storage),
        shape,
        candle_core::op::BackpropOp::none(),
        false,
    ))
}

// ── Decoder kernel pipelines ─────────────────────────────────────────────────


// ── Decoder dispatch functions ───────────────────────────────────────────────

/// GEMV: out_f16[N] = x_f16[K] @ W_f16[K,N]
pub fn triton_gemv_f16w(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, out: &Tensor,
    n: usize, k: usize,
) -> Result<()> {
    with_metal_buffers!(x, w, out, |x_buf, x_off, w_buf, w_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(w_buf), w_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n as i32));
        encoder.set_bytes(4, &(k as i32));
        encoder.set_bytes(5, &1i32);          // stride_wn = 1 (W[K,N])
        encoder.set_bytes(6, &(n as i32));    // stride_wk = N
        let grid_x = cdiv(n, 128);
        encoder.dispatch_thread_groups(
            MTLSize { width: grid_x, height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// GEMV + bias: out_f16[N] = x_f16[K] @ W_f16[K,N] + bias_f32[N]
pub fn triton_gemv_bias_f16w(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, bias: &Tensor, out: &Tensor,
    n: usize, k: usize,
) -> Result<()> {
    with_metal_buffers!(x, w, bias, out, |x_buf, x_off, w_buf, w_off, b_buf, b_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(w_buf), w_off);
        encoder.set_buffer(2, Some(b_buf), b_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(n as i32));
        encoder.set_bytes(5, &(k as i32));
        encoder.set_bytes(6, &1i32);          // stride_wn = 1
        encoder.set_bytes(7, &(n as i32));    // stride_wk = N
        let grid_x = cdiv(n, 128);
        encoder.dispatch_thread_groups(
            MTLSize { width: grid_x, height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// LayerNorm standard with f32 input: out_f16 = LN(x_f32) * weight_f16
pub fn triton_layernorm_std_f32in(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, weight: &Tensor, out: &Tensor,
    n_rows: usize, n_cols: usize,
) -> Result<()> {
    with_metal_buffers!(x, weight, out, |x_buf, x_off, w_buf, w_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(w_buf), w_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_rows as i32));
        encoder.set_bytes(4, &(n_cols as i32));
        encoder.set_bytes(5, &(n_cols as i32)); // stride_x
        encoder.set_bytes(6, &(n_cols as i32)); // stride_out
        #[cfg(target_arch = "aarch64")]
        set_air_tg_mem(&encoder, 4096); // layernorm uses 4KB shared memory
        encoder.dispatch_thread_groups(
            MTLSize { width: n_rows, height: 1, depth: 1 },
            tg_size(pipeline, 1024),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// Residual add: out_f32 = x_f16 + residual_f32
pub fn triton_residual_add_f32(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, residual: &Tensor, out: &Tensor,
    n_elements: usize,
) -> Result<()> {
    with_metal_buffers!(x, residual, out, |x_buf, x_off, r_buf, r_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(r_buf), r_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_elements as i32));
        let grid_x = cdiv(n_elements, 1024);
        encoder.dispatch_thread_groups(
            MTLSize { width: grid_x, height: 1, depth: 1 },
            tg_size(pipeline, 1024),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// Attention decode 1D (masked head_dim, BLOCK_D=128)
pub fn triton_attention_decode(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    q: &Tensor, k: &Tensor, v: &Tensor, out: &Tensor,
    kv_len: usize, head_dim: usize, n_kv_heads: usize, n_q_heads: usize,
    sm_scale: f32, stride_kv_head: usize, stride_kv_seq: usize,
) -> Result<()> {
    with_metal_buffers!(q, k, v, out, |q_buf, q_off, k_buf, k_off, v_buf, v_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(q_buf), q_off);
        encoder.set_buffer(1, Some(k_buf), k_off);
        encoder.set_buffer(2, Some(v_buf), v_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(kv_len as i32));
        encoder.set_bytes(5, &(n_q_heads as i32));
        encoder.set_bytes(6, &(n_kv_heads as i32));
        encoder.set_bytes(7, &sm_scale);
        encoder.set_bytes(8, &(stride_kv_head as i32));
        encoder.set_bytes(9, &(stride_kv_seq as i32));
        encoder.set_bytes(10, &(head_dim as i32));
        #[cfg(target_arch = "aarch64")]
        set_air_tg_mem(&encoder, 512); // attention decode uses 512B shared memory
        encoder.dispatch_thread_groups(
            MTLSize { width: n_q_heads, height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// Fused RoPE(Q) + RoPE(K) + K cache copy
pub fn triton_rope_qk_cache_fused(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    q: &Tensor, k: &Tensor, rope_table: &Tensor, cache_k: &Tensor,
    n_q_heads: usize, n_kv_heads: usize, head_dim: usize,
    half_rot: usize, pos: usize, max_kv_len: usize,
) -> Result<()> {
    with_metal_buffers!(q, k, rope_table, cache_k, |q_buf, q_off, k_buf, k_off, r_buf, r_off, c_buf, c_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(q_buf), q_off);
        encoder.set_buffer(1, Some(k_buf), k_off);
        encoder.set_buffer(2, Some(r_buf), r_off);
        encoder.set_buffer(3, Some(c_buf), c_off);
        encoder.set_bytes(4, &(n_q_heads as i32));
        encoder.set_bytes(5, &(n_kv_heads as i32));
        encoder.set_bytes(6, &(head_dim as i32));
        encoder.set_bytes(7, &(half_rot as i32));
        encoder.set_bytes(8, &(pos as i32));
        encoder.set_bytes(9, &(max_kv_len as i32));
        encoder.dispatch_thread_groups(
            MTLSize { width: 1, height: 1, depth: 1 },
            tg_size(pipeline, 512),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// KV cache append
pub fn triton_kv_cache_append(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    new_kv: &Tensor, cache: &Tensor,
    n_kv_heads: usize, head_dim: usize, max_kv_len: usize, pos: usize,
) -> Result<()> {
    let total_elems = n_kv_heads * head_dim;
    let (s0, l0) = new_kv.storage_and_layout();
    let (s1, l1) = cache.storage_and_layout();
    let off0 = l0.start_offset() * new_kv.dtype().size_in_bytes();
    let off1 = l1.start_offset() * cache.dtype().size_in_bytes();
    match (&*s0, &*s1) {
        (Storage::Metal(m0), Storage::Metal(m1)) => {
            let encoder = device.command_encoder()?;
            encoder.set_compute_pipeline_state(pipeline);
            encoder.set_buffer(0, Some(m0.buffer()), off0);
            encoder.set_buffer(1, Some(m1.buffer()), off1);
            encoder.set_bytes(2, &(total_elems as i32));
            encoder.set_bytes(3, &(max_kv_len as i32));
            encoder.set_bytes(4, &(head_dim as i32));
            encoder.set_bytes(5, &(pos as i32));
            let grid_x = cdiv(total_elems, 256);
            encoder.dispatch_thread_groups(
                MTLSize { width: grid_x, height: 1, depth: 1 },
                tg_size(pipeline, 256),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

/// Fused GLU SiLU: out = SiLU(gate) * x from packed [2*N] buffer
pub fn triton_glu_silu(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    fc1: &Tensor, out: &Tensor,
    n_elements: usize,
) -> Result<()> {
    let (s0, l0) = fc1.storage_and_layout();
    let (s1, l1) = out.storage_and_layout();
    let off0 = l0.start_offset() * fc1.dtype().size_in_bytes();
    let off1 = l1.start_offset() * out.dtype().size_in_bytes();
    match (&*s0, &*s1) {
        (Storage::Metal(m0), Storage::Metal(m1)) => {
            let encoder = device.command_encoder()?;
            encoder.set_compute_pipeline_state(pipeline);
            encoder.set_buffer(0, Some(m0.buffer()), off0);
            encoder.set_buffer(1, Some(m1.buffer()), off1);
            encoder.set_bytes(2, &(n_elements as i32));
            let grid_x = cdiv(n_elements, 1024);
            encoder.dispatch_thread_groups(
                MTLSize { width: grid_x, height: 1, depth: 1 },
                tg_size(pipeline, 1024),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

/// Fused residual-add + layernorm
pub fn triton_residual_add_layernorm(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    f16_proj: &Tensor, f32_residual: &Tensor, f32_out: &Tensor,
    weight: &Tensor, f16_norm: &Tensor,
    n_rows: usize, dim: usize,
) -> Result<()> {
    let (s0, l0) = f16_proj.storage_and_layout();
    let (s1, l1) = f32_residual.storage_and_layout();
    let (s2, l2) = f32_out.storage_and_layout();
    let (s3, l3) = weight.storage_and_layout();
    let (s4, l4) = f16_norm.storage_and_layout();
    let off0 = l0.start_offset() * f16_proj.dtype().size_in_bytes();
    let off1 = l1.start_offset() * f32_residual.dtype().size_in_bytes();
    let off2 = l2.start_offset() * f32_out.dtype().size_in_bytes();
    let off3 = l3.start_offset() * weight.dtype().size_in_bytes();
    let off4 = l4.start_offset() * f16_norm.dtype().size_in_bytes();
    match (&*s0, &*s1, &*s2, &*s3, &*s4) {
        (Storage::Metal(m0), Storage::Metal(m1), Storage::Metal(m2), Storage::Metal(m3), Storage::Metal(m4)) => {
            let encoder = device.command_encoder()?;
            encoder.set_compute_pipeline_state(pipeline);
            encoder.set_buffer(0, Some(m0.buffer()), off0);
            encoder.set_buffer(1, Some(m1.buffer()), off1);
            encoder.set_buffer(2, Some(m2.buffer()), off2);
            encoder.set_buffer(3, Some(m3.buffer()), off3);
            encoder.set_buffer(4, Some(m4.buffer()), off4);
            encoder.set_bytes(5, &(n_rows as i32));
            encoder.set_bytes(6, &(dim as i32));
            encoder.set_bytes(7, &(dim as i32)); // stride_in
            encoder.set_bytes(8, &(dim as i32)); // stride_out
            #[cfg(target_arch = "aarch64")]
            set_air_tg_mem(&encoder, 4096);
            encoder.dispatch_thread_groups(
                MTLSize { width: n_rows, height: 1, depth: 1 },
                tg_size(pipeline, 1024),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

/// Fused GEMV + bias + GLU-SiLU
pub fn triton_gemv_bias_glu(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, bias: &Tensor, out: &Tensor,
    n_intermediate: usize, k: usize,
) -> Result<()> {
    with_metal_buffers!(x, w, bias, out, |x_buf, x_off, w_buf, w_off, b_buf, b_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(w_buf), w_off);
        encoder.set_buffer(2, Some(b_buf), b_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(n_intermediate as i32));
        encoder.set_bytes(5, &(k as i32));
        encoder.set_bytes(6, &1i32);                               // stride_wn = 1
        encoder.set_bytes(7, &((n_intermediate * 2) as i32));      // stride_wk = 2*N
        let grid_x = cdiv(n_intermediate, 128);
        encoder.dispatch_thread_groups(
            MTLSize { width: grid_x, height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// Fused GEMV + residual-add + layernorm
pub fn triton_gemv_resadd_ln(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor,
    f32_res: &Tensor, f32_out: &Tensor,
    ln_weight: &Tensor, f16_norm: &Tensor,
    dim: usize, gemv_k: usize,
) -> Result<()> {
    let (s0, l0) = x.storage_and_layout();
    let (s1, l1) = w.storage_and_layout();
    let (s2, l2) = f32_res.storage_and_layout();
    let (s3, l3) = f32_out.storage_and_layout();
    let (s4, l4) = ln_weight.storage_and_layout();
    let (s5, l5) = f16_norm.storage_and_layout();
    let off0 = l0.start_offset() * x.dtype().size_in_bytes();
    let off1 = l1.start_offset() * w.dtype().size_in_bytes();
    let off2 = l2.start_offset() * f32_res.dtype().size_in_bytes();
    let off3 = l3.start_offset() * f32_out.dtype().size_in_bytes();
    let off4 = l4.start_offset() * ln_weight.dtype().size_in_bytes();
    let off5 = l5.start_offset() * f16_norm.dtype().size_in_bytes();
    match (&*s0, &*s1, &*s2, &*s3, &*s4, &*s5) {
        (Storage::Metal(m0), Storage::Metal(m1), Storage::Metal(m2), Storage::Metal(m3), Storage::Metal(m4), Storage::Metal(m5)) => {
            let encoder = device.command_encoder()?;
            encoder.set_compute_pipeline_state(pipeline);
            encoder.set_buffer(0, Some(m0.buffer()), off0);
            encoder.set_buffer(1, Some(m1.buffer()), off1);
            encoder.set_buffer(2, Some(m2.buffer()), off2);
            encoder.set_buffer(3, Some(m3.buffer()), off3);
            encoder.set_buffer(4, Some(m4.buffer()), off4);
            encoder.set_buffer(5, Some(m5.buffer()), off5);
            encoder.set_bytes(6, &(dim as i32));
            encoder.set_bytes(7, &(gemv_k as i32));
            encoder.set_bytes(8, &1i32);          // stride_wn = 1
            encoder.set_bytes(9, &(dim as i32));  // stride_wk = dim
            #[cfg(target_arch = "aarch64")]
            set_air_tg_mem(&encoder, 4096); // gemv_resadd_ln has fused layernorm
            encoder.dispatch_thread_groups(
                MTLSize { width: 1, height: 1, depth: 1 },
                tg_size(pipeline, 1024),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

// ── Batched dispatch (shared encoder, MetalBuffer) ──────────────────────────
// These variants accept a &ComputeCommandEncoder + &GpuBuffer, allowing ~200
// dispatches per decoder token to share a single encoder. No Tensor overhead.

use candle_metal_kernels::metal::ComputeCommandEncoder;

pub fn enc_gemv_f16w(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &GpuBuffer, w: &GpuBuffer, out: &GpuBuffer, n: usize, k: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(x.buf()), x.offset);
    enc.set_buffer(1, Some(w.buf()), w.offset);
    enc.set_buffer(2, Some(out.buf()), out.offset);
    enc.set_bytes(3, &(n as i32));
    enc.set_bytes(4, &(k as i32));
    enc.set_bytes(5, &1i32);
    enc.set_bytes(6, &(n as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: cdiv(n, 128), height: 1, depth: 1 },
        tg_size(pipeline, 128),
    );
}

pub fn enc_layernorm_std_f32in(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &GpuBuffer, weight: &GpuBuffer, out: &GpuBuffer, n_rows: usize, n_cols: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(x.buf()), x.offset);
    enc.set_buffer(1, Some(weight.buf()), weight.offset);
    enc.set_buffer(2, Some(out.buf()), out.offset);
    enc.set_bytes(3, &(n_rows as i32));
    enc.set_bytes(4, &(n_cols as i32));
    enc.set_bytes(5, &(n_cols as i32));
    enc.set_bytes(6, &(n_cols as i32));
    #[cfg(target_arch = "aarch64")]
    set_air_tg_mem(enc, 4096);
    enc.dispatch_thread_groups(
        MTLSize { width: n_rows, height: 1, depth: 1 },
        tg_size(pipeline, 1024),
    );
}

pub fn enc_attention_decode(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    q: &GpuBuffer, k: &GpuBuffer, v: &GpuBuffer, out: &GpuBuffer,
    kv_len: usize, head_dim: usize, n_kv_heads: usize, n_q_heads: usize,
    sm_scale: f32, stride_kv_head: usize, stride_kv_seq: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(q.buf()), q.offset);
    enc.set_buffer(1, Some(k.buf()), k.offset);
    enc.set_buffer(2, Some(v.buf()), v.offset);
    enc.set_buffer(3, Some(out.buf()), out.offset);
    enc.set_bytes(4, &(kv_len as i32));
    enc.set_bytes(5, &(n_q_heads as i32));
    enc.set_bytes(6, &(n_kv_heads as i32));
    enc.set_bytes(7, &sm_scale);
    enc.set_bytes(8, &(stride_kv_head as i32));
    enc.set_bytes(9, &(stride_kv_seq as i32));
    enc.set_bytes(10, &(head_dim as i32));
    #[cfg(target_arch = "aarch64")]
    set_air_tg_mem(enc, 512);
    enc.dispatch_thread_groups(
        MTLSize { width: n_q_heads, height: 1, depth: 1 },
        tg_size(pipeline, 128),
    );
}

pub fn enc_attention_splitkv(
    enc: &ComputeCommandEncoder,
    partial_pipeline: &ComputePipeline, reduce_pipeline: &ComputePipeline,
    q: &GpuBuffer, k: &GpuBuffer, v: &GpuBuffer, out: &GpuBuffer, partial_buf: &GpuBuffer,
    kv_len: usize, head_dim: usize, n_kv_heads: usize, n_q_heads: usize,
    sm_scale: f32, stride_kv_head: usize, stride_kv_seq: usize,
    n_splits: usize,
) {
    let kv_per_split = (kv_len + n_splits - 1) / n_splits;
    let block_d = 128usize;
    let stride_partial = 3 * block_d;

    // Phase 1: partial attention per (head, split)
    enc.set_compute_pipeline_state(partial_pipeline);
    enc.set_buffer(0, Some(q.buf()), q.offset);
    enc.set_buffer(1, Some(k.buf()), k.offset);
    enc.set_buffer(2, Some(v.buf()), v.offset);
    enc.set_buffer(3, Some(partial_buf.buf()), partial_buf.offset);
    enc.set_bytes(4, &(kv_len as i32));
    enc.set_bytes(5, &(n_q_heads as i32));
    enc.set_bytes(6, &(n_kv_heads as i32));
    enc.set_bytes(7, &sm_scale);
    enc.set_bytes(8, &(stride_kv_head as i32));
    enc.set_bytes(9, &(stride_kv_seq as i32));
    enc.set_bytes(10, &(head_dim as i32));
    enc.set_bytes(11, &(n_splits as i32));
    enc.set_bytes(12, &(kv_per_split as i32));
    enc.set_bytes(13, &(stride_partial as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: n_q_heads * n_splits, height: 1, depth: 1 },
        tg_size(partial_pipeline, 128),
    );

    // Phase 2: reduce partials to final output
    enc.set_compute_pipeline_state(reduce_pipeline);
    enc.set_buffer(0, Some(partial_buf.buf()), partial_buf.offset);
    enc.set_buffer(1, Some(out.buf()), out.offset);
    enc.set_bytes(2, &(n_q_heads as i32));
    enc.set_bytes(3, &(n_splits as i32));
    enc.set_bytes(4, &(head_dim as i32));
    enc.set_bytes(5, &(stride_partial as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: n_q_heads, height: 1, depth: 1 },
        tg_size(reduce_pipeline, 128),
    );
}

pub fn enc_rope_qk_cache_fused(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    q: &GpuBuffer, k: &GpuBuffer, rope_table: &GpuBuffer, cache_k: &GpuBuffer,
    n_q_heads: usize, n_kv_heads: usize, head_dim: usize,
    half_rot: usize, pos: usize, max_kv_len: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(q.buf()), q.offset);
    enc.set_buffer(1, Some(k.buf()), k.offset);
    enc.set_buffer(2, Some(rope_table.buf()), rope_table.offset);
    enc.set_buffer(3, Some(cache_k.buf()), cache_k.offset);
    enc.set_bytes(4, &(n_q_heads as i32));
    enc.set_bytes(5, &(n_kv_heads as i32));
    enc.set_bytes(6, &(head_dim as i32));
    enc.set_bytes(7, &(half_rot as i32));
    enc.set_bytes(8, &(pos as i32));
    enc.set_bytes(9, &(max_kv_len as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: 1, height: 1, depth: 1 },
        tg_size(pipeline, 512),
    );
}

pub fn enc_kv_cache_append(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    new_kv: &GpuBuffer, cache: &GpuBuffer,
    n_kv_heads: usize, head_dim: usize, max_kv_len: usize, pos: usize,
) {
    let total_elems = n_kv_heads * head_dim;
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(new_kv.buf()), new_kv.offset);
    enc.set_buffer(1, Some(cache.buf()), cache.offset);
    enc.set_bytes(2, &(total_elems as i32));
    enc.set_bytes(3, &(max_kv_len as i32));
    enc.set_bytes(4, &(head_dim as i32));
    enc.set_bytes(5, &(pos as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: cdiv(total_elems, 256), height: 1, depth: 1 },
        tg_size(pipeline, 256),
    );
}

pub fn enc_residual_add_layernorm(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    f16_proj: &GpuBuffer, f32_residual: &GpuBuffer, f32_out: &GpuBuffer,
    weight: &GpuBuffer, f16_norm: &GpuBuffer,
    n_rows: usize, dim: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(f16_proj.buf()), f16_proj.offset);
    enc.set_buffer(1, Some(f32_residual.buf()), f32_residual.offset);
    enc.set_buffer(2, Some(f32_out.buf()), f32_out.offset);
    enc.set_buffer(3, Some(weight.buf()), weight.offset);
    enc.set_buffer(4, Some(f16_norm.buf()), f16_norm.offset);
    enc.set_bytes(5, &(n_rows as i32));
    enc.set_bytes(6, &(dim as i32));
    enc.set_bytes(7, &(dim as i32));
    enc.set_bytes(8, &(dim as i32));
    #[cfg(target_arch = "aarch64")]
    set_air_tg_mem(enc, 4096);
    enc.dispatch_thread_groups(
        MTLSize { width: n_rows, height: 1, depth: 1 },
        tg_size(pipeline, 1024),
    );
}

pub fn enc_gemv_splitk_bias(
    enc: &ComputeCommandEncoder,
    partial_pipeline: &ComputePipeline, reduce_pipeline: &ComputePipeline,
    x: &GpuBuffer, w: &GpuBuffer, bias: &GpuBuffer, out: &GpuBuffer, partial_buf: &GpuBuffer,
    n: usize, k: usize, n_splits: usize,
) {
    let k_per_split = k / n_splits;
    let n_n_blocks = cdiv(n, 128);
    let stride_wk = n;
    let stride_partial = n;

    // Phase 1: partial GEMV
    enc.set_compute_pipeline_state(partial_pipeline);
    enc.set_buffer(0, Some(x.buf()), x.offset);
    enc.set_buffer(1, Some(w.buf()), w.offset);
    enc.set_buffer(2, Some(partial_buf.buf()), partial_buf.offset);
    enc.set_bytes(3, &(n as i32));
    enc.set_bytes(4, &(k as i32));
    enc.set_bytes(5, &(stride_wk as i32));
    enc.set_bytes(6, &(n_n_blocks as i32));
    enc.set_bytes(7, &(k_per_split as i32));
    enc.set_bytes(8, &(stride_partial as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: n_n_blocks * n_splits, height: 1, depth: 1 },
        tg_size(partial_pipeline, 128),
    );
    // Phase 2: reduce + bias
    enc.set_compute_pipeline_state(reduce_pipeline);
    enc.set_buffer(0, Some(partial_buf.buf()), partial_buf.offset);
    enc.set_buffer(1, Some(bias.buf()), bias.offset);
    enc.set_buffer(2, Some(out.buf()), out.offset);
    enc.set_bytes(3, &(n as i32));
    enc.set_bytes(4, &(n_splits as i32));
    enc.set_bytes(5, &(stride_partial as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: n_n_blocks, height: 1, depth: 1 },
        tg_size(reduce_pipeline, 128),
    );
}

pub fn enc_gemv_splitk(
    enc: &ComputeCommandEncoder,
    partial_pipeline: &ComputePipeline, reduce_pipeline: &ComputePipeline,
    x: &GpuBuffer, w: &GpuBuffer, out: &GpuBuffer, partial_buf: &GpuBuffer,
    n: usize, k: usize, n_splits: usize,
) {
    let k_per_split = k / n_splits;
    let n_n_blocks = cdiv(n, 128);
    let stride_wk = n;
    let stride_partial = n;

    // Phase 1: partial GEMV
    enc.set_compute_pipeline_state(partial_pipeline);
    enc.set_buffer(0, Some(x.buf()), x.offset);
    enc.set_buffer(1, Some(w.buf()), w.offset);
    enc.set_buffer(2, Some(partial_buf.buf()), partial_buf.offset);
    enc.set_bytes(3, &(n as i32));
    enc.set_bytes(4, &(k as i32));
    enc.set_bytes(5, &(stride_wk as i32));
    enc.set_bytes(6, &(n_n_blocks as i32));
    enc.set_bytes(7, &(k_per_split as i32));
    enc.set_bytes(8, &(stride_partial as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: n_n_blocks * n_splits, height: 1, depth: 1 },
        tg_size(partial_pipeline, 128),
    );
    // Phase 2: reduce
    enc.set_compute_pipeline_state(reduce_pipeline);
    enc.set_buffer(0, Some(partial_buf.buf()), partial_buf.offset);
    enc.set_buffer(1, Some(out.buf()), out.offset);
    enc.set_bytes(2, &(n as i32));
    enc.set_bytes(3, &(n_splits as i32));
    enc.set_bytes(4, &(stride_partial as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: n_n_blocks, height: 1, depth: 1 },
        tg_size(reduce_pipeline, 128),
    );
}

pub fn enc_gemv_qkv_splitk(
    enc: &ComputeCommandEncoder,
    partial_pipeline: &ComputePipeline, reduce_pipeline: &ComputePipeline,
    x: &GpuBuffer, wq: &GpuBuffer, wk: &GpuBuffer, wv: &GpuBuffer,
    oq: &GpuBuffer, ok: &GpuBuffer, ov: &GpuBuffer,
    partial_buf: &GpuBuffer,
    n: usize, k: usize, n_splits: usize,
) {
    let k_per_split = k / n_splits;
    let n_n_blocks = cdiv(n, 128);
    let stride_wk = n;
    let stride_partial = n;

    // Phase 1: fused QKV partial (grid: n_n_blocks*n_splits × 3)
    enc.set_compute_pipeline_state(partial_pipeline);
    enc.set_buffer(0, Some(x.buf()), x.offset);
    enc.set_buffer(1, Some(wq.buf()), wq.offset);
    enc.set_buffer(2, Some(wk.buf()), wk.offset);
    enc.set_buffer(3, Some(wv.buf()), wv.offset);
    enc.set_buffer(4, Some(partial_buf.buf()), partial_buf.offset);
    enc.set_bytes(5, &(n as i32));
    enc.set_bytes(6, &(k as i32));
    enc.set_bytes(7, &(stride_wk as i32));
    enc.set_bytes(8, &(n_n_blocks as i32));
    enc.set_bytes(9, &(k_per_split as i32));
    enc.set_bytes(10, &(stride_partial as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: n_n_blocks * n_splits, height: 3, depth: 1 },
        tg_size(partial_pipeline, 128),
    );
    // Phase 2: fused QKV reduce (grid: cdiv(N,128) × 3)
    enc.set_compute_pipeline_state(reduce_pipeline);
    enc.set_buffer(0, Some(partial_buf.buf()), partial_buf.offset);
    enc.set_buffer(1, Some(oq.buf()), oq.offset);
    enc.set_buffer(2, Some(ok.buf()), ok.offset);
    enc.set_buffer(3, Some(ov.buf()), ov.offset);
    enc.set_bytes(4, &(n as i32));
    enc.set_bytes(5, &(n_splits as i32));
    enc.set_bytes(6, &(stride_partial as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: n_n_blocks, height: 3, depth: 1 },
        tg_size(reduce_pipeline, 128),
    );
}

pub fn enc_gemv_glu_splitk(
    enc: &ComputeCommandEncoder,
    partial_pipeline: &ComputePipeline, reduce_pipeline: &ComputePipeline,
    x: &GpuBuffer, w: &GpuBuffer, bias: &GpuBuffer, out: &GpuBuffer, partial_buf: &GpuBuffer,
    n_intermediate: usize, k: usize, n_splits: usize,
) {
    let k_per_split = k / n_splits;
    let n_n_blocks = cdiv(n_intermediate, 128);
    let stride_wk = n_intermediate * 2;
    let stride_partial = n_intermediate * 2;

    // Phase 1: partial GEMV (x-half + gate-half)
    enc.set_compute_pipeline_state(partial_pipeline);
    enc.set_buffer(0, Some(x.buf()), x.offset);
    enc.set_buffer(1, Some(w.buf()), w.offset);
    enc.set_buffer(2, Some(partial_buf.buf()), partial_buf.offset);
    enc.set_bytes(3, &(n_intermediate as i32));
    enc.set_bytes(4, &(k as i32));
    enc.set_bytes(5, &(stride_wk as i32));
    enc.set_bytes(6, &(n_n_blocks as i32));
    enc.set_bytes(7, &(k_per_split as i32));
    enc.set_bytes(8, &(stride_partial as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: n_n_blocks * n_splits, height: 1, depth: 1 },
        tg_size(partial_pipeline, 128),
    );
    // Phase 2: reduce + bias + GLU-SiLU
    enc.set_compute_pipeline_state(reduce_pipeline);
    enc.set_buffer(0, Some(partial_buf.buf()), partial_buf.offset);
    enc.set_buffer(1, Some(bias.buf()), bias.offset);
    enc.set_buffer(2, Some(out.buf()), out.offset);
    enc.set_bytes(3, &(n_intermediate as i32));
    enc.set_bytes(4, &(n_splits as i32));
    enc.set_bytes(5, &(stride_partial as i32));
    enc.dispatch_thread_groups(
        MTLSize { width: n_n_blocks, height: 1, depth: 1 },
        tg_size(reduce_pipeline, 128),
    );
}

/// Tiled matmul on MetalBuffer: C[M,N] = A[M,K] @ B[K,N]
pub fn enc_matmul(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    a: &GpuBuffer, b: &GpuBuffer, out: &GpuBuffer,
    m: usize, n: usize, k: usize, block_m: usize, block_n: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(a.buf()), a.offset);
    enc.set_buffer(1, Some(b.buf()), b.offset);
    enc.set_buffer(2, Some(out.buf()), out.offset);
    enc.set_bytes(3, &(m as i32));
    enc.set_bytes(4, &(n as i32));
    enc.set_bytes(5, &(k as i32));
    enc.set_bytes(6, &(k as i32));      // stride_am = K
    enc.set_bytes(7, &1i32);            // stride_ak = 1
    enc.set_bytes(8, &(n as i32));      // stride_bk = N
    enc.set_bytes(9, &1i32);            // stride_bn = 1
    enc.set_bytes(10, &(n as i32));     // stride_cm = N
    enc.set_bytes(11, &1i32);           // stride_cn = 1
    let grid = MTLSize {
        width: cdiv(m, block_m),
        height: cdiv(n, block_n),
        depth: 1,
    };
    #[cfg(target_arch = "aarch64")]
    if block_m <= 32 { set_air_tg_mem(enc, 4096); }
    enc.dispatch_thread_groups(grid, matmul_tg_size(pipeline, block_m, block_n));
}

pub fn enc_matmul_bias(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    a: &GpuBuffer, b: &GpuBuffer, bias: &GpuBuffer, out: &GpuBuffer,
    m: usize, n: usize, k: usize, block_m: usize, block_n: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(a.buf()), a.offset);
    enc.set_buffer(1, Some(b.buf()), b.offset);
    enc.set_buffer(2, Some(bias.buf()), bias.offset);
    enc.set_buffer(3, Some(out.buf()), out.offset);
    enc.set_bytes(4, &(m as i32));
    enc.set_bytes(5, &(n as i32));
    enc.set_bytes(6, &(k as i32));
    enc.set_bytes(7, &(k as i32));      // stride_am = K
    enc.set_bytes(8, &1i32);            // stride_ak = 1
    enc.set_bytes(9, &(n as i32));      // stride_bk = N
    enc.set_bytes(10, &1i32);           // stride_bn = 1
    enc.set_bytes(11, &(n as i32));     // stride_cm = N
    enc.set_bytes(12, &1i32);           // stride_cn = 1
    let grid = MTLSize {
        width: cdiv(m, block_m),
        height: cdiv(n, block_n),
        depth: 1,
    };
    #[cfg(target_arch = "aarch64")]
    if block_m <= 32 { set_air_tg_mem(enc, 4096); }
    enc.dispatch_thread_groups(grid, matmul_tg_size(pipeline, block_m, block_n));
}

pub fn enc_matmul_bias_gelu(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    a: &GpuBuffer, b: &GpuBuffer, bias: &GpuBuffer, out: &GpuBuffer,
    m: usize, n: usize, k: usize, block_m: usize, block_n: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(a.buf()), a.offset);
    enc.set_buffer(1, Some(b.buf()), b.offset);
    enc.set_buffer(2, Some(bias.buf()), bias.offset);
    enc.set_buffer(3, Some(out.buf()), out.offset);
    enc.set_bytes(4, &(m as i32));
    enc.set_bytes(5, &(n as i32));
    enc.set_bytes(6, &(k as i32));
    enc.set_bytes(7, &(k as i32));      // stride_am = K
    enc.set_bytes(8, &1i32);            // stride_ak = 1
    enc.set_bytes(9, &(n as i32));      // stride_bk = N
    enc.set_bytes(10, &1i32);           // stride_bn = 1
    enc.set_bytes(11, &(n as i32));     // stride_cm = N
    enc.set_bytes(12, &1i32);           // stride_cn = 1
    let grid = MTLSize {
        width: cdiv(m, block_m),
        height: cdiv(n, block_n),
        depth: 1,
    };
    #[cfg(target_arch = "aarch64")]
    if block_m <= 32 { set_air_tg_mem(enc, 4096); }
    enc.dispatch_thread_groups(grid, matmul_tg_size(pipeline, block_m, block_n));
}

pub fn enc_layernorm_bare(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &GpuBuffer, out: &GpuBuffer,
    n_rows: usize, n_cols: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(x.buf()), x.offset);
    enc.set_buffer(1, Some(out.buf()), out.offset);
    enc.set_bytes(2, &(n_rows as i32));
    enc.set_bytes(3, &(n_cols as i32));
    enc.set_bytes(4, &(n_cols as i32));
    enc.set_bytes(5, &(n_cols as i32));
    let grid = MTLSize { width: n_rows, height: 1, depth: 1 };
    #[cfg(target_arch = "aarch64")]
    set_air_tg_mem(enc, 4096);
    enc.dispatch_thread_groups(grid, tg_size(pipeline, n_cols));
}

pub fn enc_layernorm_unit_offset(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &GpuBuffer, gamma: &GpuBuffer, out: &GpuBuffer,
    n_rows: usize, n_cols: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(x.buf()), x.offset);
    enc.set_buffer(1, Some(gamma.buf()), gamma.offset);
    enc.set_buffer(2, Some(out.buf()), out.offset);
    enc.set_bytes(3, &(n_rows as i32));
    enc.set_bytes(4, &(n_cols as i32));
    enc.set_bytes(5, &(n_cols as i32));
    enc.set_bytes(6, &(n_cols as i32));
    let grid = MTLSize { width: n_rows, height: 1, depth: 1 };
    #[cfg(target_arch = "aarch64")]
    set_air_tg_mem(enc, 4096);
    enc.dispatch_thread_groups(grid, tg_size(pipeline, n_cols));
}

pub fn enc_gelu(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &GpuBuffer, out: &GpuBuffer, n_elements: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(x.buf()), x.offset);
    enc.set_buffer(1, Some(out.buf()), out.offset);
    enc.set_bytes(2, &(n_elements as i32));
    let grid = MTLSize { width: cdiv(n_elements, 1024), height: 1, depth: 1 };
    enc.dispatch_thread_groups(grid, tg_size(pipeline, 1024));
}

pub fn enc_residual_add(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &GpuBuffer, residual: &GpuBuffer, out: &GpuBuffer, n_elements: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(x.buf()), x.offset);
    enc.set_buffer(1, Some(residual.buf()), residual.offset);
    enc.set_buffer(2, Some(out.buf()), out.offset);
    enc.set_bytes(3, &(n_elements as i32));
    let tg_w = tg_size(pipeline, 1024).width;
    let grid = MTLSize { width: cdiv(n_elements, tg_w), height: 1, depth: 1 };
    enc.dispatch_thread_groups(grid, MTLSize { width: tg_w, height: 1, depth: 1 });
}

pub fn enc_bias_add(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &GpuBuffer, bias: &GpuBuffer, out: &GpuBuffer, n_elements: usize, n_cols: usize,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(x.buf()), x.offset);
    enc.set_buffer(1, Some(bias.buf()), bias.offset);
    enc.set_buffer(2, Some(out.buf()), out.offset);
    enc.set_bytes(3, &(n_elements as i32));
    enc.set_bytes(4, &(n_cols as i32));
    let tg_w = tg_size(pipeline, 1024).width;
    let grid = MTLSize { width: cdiv(n_elements, tg_w), height: 1, depth: 1 };
    enc.dispatch_thread_groups(grid, MTLSize { width: tg_w, height: 1, depth: 1 });
}

pub fn enc_flash_attention(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    q: &GpuBuffer, k: &GpuBuffer, v: &GpuBuffer, out: &GpuBuffer,
    n_heads: usize, seq_len: usize, head_dim: usize,
    stride_h: i32, stride_m: i32, stride_o: i32,
    sm_scale: f32, window_left: i32, window_right: i32,
) {
    enc.set_compute_pipeline_state(pipeline);
    enc.set_buffer(0, Some(q.buf()), q.offset);
    enc.set_buffer(1, Some(k.buf()), k.offset);
    enc.set_buffer(2, Some(v.buf()), v.offset);
    enc.set_buffer(3, Some(out.buf()), out.offset);
    enc.set_bytes(4, &(seq_len as i32));
    enc.set_bytes(5, &stride_h);
    enc.set_bytes(6, &stride_m);
    enc.set_bytes(7, &stride_o);
    enc.set_bytes(8, &sm_scale);
    enc.set_bytes(9, &window_left);
    enc.set_bytes(10, &window_right);
    #[cfg(target_arch = "aarch64")]
    enc.set_threadgroup_memory_length(0, 8192);
    let grid = MTLSize {
        width: cdiv(seq_len, 32),
        height: n_heads,
        depth: 1,
    };
    let _ = head_dim; // used implicitly by kernel
    enc.dispatch_thread_groups(grid, fa_tg_size(pipeline));
}

