//! Triton-compiled Metal kernel dispatch for Moonshine encoder.
//!
//! Loads pre-compiled .metal source files (generated by Triton AOT compiler),
//! compiles them into Metal compute pipelines, and provides dispatch functions
//! for each kernel type.

use anyhow::Result;
use candle_core::{DType, MetalDevice, MetalStorage, Shape, Storage, Tensor};
use candle_metal_kernels::metal::ComputePipeline;
use objc2_metal::MTLSize;
use std::path::{Path, PathBuf};

// Embed all .metal kernel sources at compile time so the binary is self-contained.
// Uses cfg(target_arch) to select Apple Silicon vs Intel shader variants.
macro_rules! embed_kernels {
    ($dir:literal; $($name:literal),* $(,)?) => {
        fn embedded_metal_source(name: &str) -> Option<&'static str> {
            match name {
                $($name => Some(include_str!(concat!(
                    "../../triton/third_party/metal/", $dir, "/", $name, ".metal"
                ))),)*
                _ => None,
            }
        }
    }
}

// Shared kernel list — only the directory and arch-specific extras differ.
macro_rules! metal_kernels {
    ($dir:literal $(, $extra:literal)*) => {
        embed_kernels!($dir;
            // Encoder
            "matmul_fp16_64x64x32",
            "matmul_fp16_128x128x32",
            "matmul_bias_fp16_32x32x32",
            "matmul_bias_fp16_64x64x32",
            "matmul_bias_fp16_128x128x32",
            "matmul_bias_gelu_fp16_32x32x32",
            "matmul_bias_gelu_fp16_64x64x32",
            "matmul_bias_gelu_fp16_128x128x32",
            "layernorm_unit_offset_768",
            "layernorm_bare_768",
            "residual_add_fp16",
            "flash_attention_fwd_32x32x64",
            "gelu_fp16",
            "bias_add_fp16",
            // Decoder
            "gemv_f16w",
            "gemv_bias_f16w",
            "layernorm_standard_f32in_640",
            "residual_add_f32",
            "convert_f32_to_f16",
            "attention_decode_1d_d80",
            "attention_decode_splitkv_partial",
            "attention_decode_splitkv_reduce",
            "rope_qk_cache_fused",
            "kv_cache_append",
            "glu_silu_fused",
            "residual_add_layernorm_fused",
            "gemv_bias_glu_fused",
            "gemv_resadd_ln_fused",
            "gemv_splitk_partial",
            "gemv_splitk_bias_reduce",
            "gemv_splitk_reduce",
            "gemv_splitk_reduce_resadd_ln",
            "gemv_qkv_splitk_partial",
            "gemv_qkv_splitk_reduce",
            "gemv_glu_splitk_partial",
            "gemv_glu_splitk_reduce",
            $($extra,)*
        );
    }
}

#[cfg(target_arch = "aarch64")]
metal_kernels!("moonshine_metal");

#[cfg(target_arch = "x86_64")]
metal_kernels!("moonshine_metal_intel", "rel_pos_fa2_fwd_16x32x128");

fn cdiv(a: usize, b: usize) -> usize {
    (a + b - 1) / b
}

/// Clamp threadgroup size to pipeline's maximum (critical for Intel GPUs with < 1024 limit).
fn tg_size(pipeline: &ComputePipeline, requested: usize) -> MTLSize {
    let max = pipeline.max_total_threads_per_threadgroup();
    MTLSize { width: requested.min(max), height: 1, depth: 1 }
}

/// All compiled Triton kernel pipelines for the Moonshine encoder.
pub struct TritonKernels {
    pub matmul_64x64: ComputePipeline,
    pub matmul_128x128: Option<ComputePipeline>,
    pub matmul_bias_32x32: ComputePipeline,
    pub matmul_bias_64x64: Option<ComputePipeline>,
    pub matmul_bias_128x128: Option<ComputePipeline>,
    pub matmul_bias_gelu_32x32: ComputePipeline,
    pub matmul_bias_gelu_64x64: Option<ComputePipeline>,
    pub matmul_bias_gelu_128x128: Option<ComputePipeline>,
    pub layernorm_unit_offset: ComputePipeline,
    pub layernorm_bare: Option<ComputePipeline>,
    pub residual_add: ComputePipeline,
    pub flash_attention: ComputePipeline,
    pub rel_pos_fa2: Option<ComputePipeline>,
    pub gelu: ComputePipeline,
    pub bias_add: ComputePipeline,
}

impl TritonKernels {
    /// Load kernels from embedded .metal sources (or fall back to disk).
    pub fn load(metal_device: &MetalDevice, kernel_dir: &Path) -> Result<Self> {
        let device = metal_device.device();

        let load = |name: &str, func_name: &str| -> Result<ComputePipeline> {
            eprint!("    {name}...");
            let owned;
            let source = match embedded_metal_source(name) {
                Some(s) => s,
                None => {
                    let path = kernel_dir.join(format!("{name}.metal"));
                    owned = std::fs::read_to_string(&path)
                        .map_err(|e| anyhow::anyhow!("Failed to read {}: {e}", path.display()))?;
                    &owned
                }
            };
            let lib = device
                .new_library_with_source(source, None)
                .map_err(|e| anyhow::anyhow!("Failed to compile {name}: {e}"))?;
            let func = lib
                .get_function(func_name, None)
                .map_err(|e| anyhow::anyhow!("Function {func_name} not found in {name}: {e}"))?;
            let pipeline = device
                .new_compute_pipeline_state_with_function(&func)
                .map_err(|e| anyhow::anyhow!("Pipeline failed for {name}: {e}"))?;
            eprintln!(" ok (max_threads={})", pipeline.max_total_threads_per_threadgroup());
            Ok(pipeline)
        };

        Ok(Self {
            matmul_64x64: load("matmul_fp16_64x64x32", "matmul_fp16")?,
            matmul_128x128: load("matmul_fp16_128x128x32", "matmul_fp16").ok(),
            matmul_bias_32x32: load("matmul_bias_fp16_32x32x32", "matmul_bias_fp16")?,
            matmul_bias_64x64: {
                match load("matmul_bias_fp16_64x64x32", "matmul_bias_fp16") {
                    Ok(p) => Some(p),
                    Err(e) => { eprintln!(" SKIP ({e})"); None }
                }
            },
            matmul_bias_128x128: {
                match load("matmul_bias_fp16_128x128x32", "matmul_bias_fp16") {
                    Ok(p) => Some(p),
                    Err(e) => { eprintln!(" SKIP ({e})"); None }
                }
            },
            matmul_bias_gelu_32x32: load("matmul_bias_gelu_fp16_32x32x32", "matmul_bias_gelu_fp16")?,
            matmul_bias_gelu_64x64: {
                match load("matmul_bias_gelu_fp16_64x64x32", "matmul_bias_gelu_fp16") {
                    Ok(p) => Some(p),
                    Err(e) => { eprintln!(" SKIP ({e})"); None }
                }
            },
            matmul_bias_gelu_128x128: {
                match load("matmul_bias_gelu_fp16_128x128x32", "matmul_bias_gelu_fp16") {
                    Ok(p) => Some(p),
                    Err(e) => { eprintln!(" SKIP ({e})"); None }
                }
            },
            layernorm_unit_offset: load("layernorm_unit_offset_768", "layernorm_unit_offset")?,
            layernorm_bare: load("layernorm_bare_768", "layernorm_bare").ok(),
            residual_add: load("residual_add_fp16", "residual_add")?,
            flash_attention: load("flash_attention_fwd_32x32x64", "flash_attention_fwd")?,
            rel_pos_fa2: load("rel_pos_fa2_fwd_16x32x128", "rel_pos_fa2_fwd").ok(),
            gelu: load("gelu_fp16", "gelu_forward")?,
            bias_add: load("bias_add_fp16", "bias_add")?,
        })
    }
}

/// Create an empty F16 output tensor on the Metal device.
pub fn empty_f16(device: &MetalDevice, shape: impl Into<Shape>) -> Result<Tensor> {
    let shape: Shape = shape.into();
    let n = shape.elem_count();
    let buffer = device.new_buffer(n, DType::F16, "triton_out")?;
    let storage = MetalStorage::new(buffer, device.clone(), n, DType::F16);
    Ok(Tensor::from_storage(
        Storage::Metal(storage),
        shape,
        candle_core::op::BackpropOp::none(),
        false,
    ))
}

/// Helper: extract MetalStorage from a tensor. Panics on non-Metal tensor.
macro_rules! with_metal_buffers {
    // 3 tensors + output
    ($a:expr, $b:expr, $c:expr, $out:expr, |$a_buf:ident, $a_off:ident, $b_buf:ident, $b_off:ident, $c_buf:ident, $c_off:ident, $o_buf:ident, $o_off:ident| $body:block) => {{
        let (sa, la) = $a.storage_and_layout();
        let (sb, lb) = $b.storage_and_layout();
        let (sc, lc) = $c.storage_and_layout();
        let (so, lo) = $out.storage_and_layout();
        let $a_off = la.start_offset() * $a.dtype().size_in_bytes();
        let $b_off = lb.start_offset() * $b.dtype().size_in_bytes();
        let $c_off = lc.start_offset() * $c.dtype().size_in_bytes();
        let $o_off = lo.start_offset() * $out.dtype().size_in_bytes();
        match (&*sa, &*sb, &*sc, &*so) {
            (Storage::Metal(ma), Storage::Metal(mb), Storage::Metal(mc), Storage::Metal(mo)) => {
                let $a_buf = ma.buffer();
                let $b_buf = mb.buffer();
                let $c_buf = mc.buffer();
                let $o_buf = mo.buffer();
                $body
            }
            _ => anyhow::bail!("All tensors must be on Metal device"),
        }
    }};
    // 2 tensors + output
    ($a:expr, $b:expr, $out:expr, |$a_buf:ident, $a_off:ident, $b_buf:ident, $b_off:ident, $o_buf:ident, $o_off:ident| $body:block) => {{
        let (sa, la) = $a.storage_and_layout();
        let (sb, lb) = $b.storage_and_layout();
        let (so, lo) = $out.storage_and_layout();
        let $a_off = la.start_offset() * $a.dtype().size_in_bytes();
        let $b_off = lb.start_offset() * $b.dtype().size_in_bytes();
        let $o_off = lo.start_offset() * $out.dtype().size_in_bytes();
        match (&*sa, &*sb, &*so) {
            (Storage::Metal(ma), Storage::Metal(mb), Storage::Metal(mo)) => {
                let $a_buf = ma.buffer();
                let $b_buf = mb.buffer();
                let $o_buf = mo.buffer();
                $body
            }
            _ => anyhow::bail!("All tensors must be on Metal device"),
        }
    }};
}

// ── Dispatch functions ──────────────────────────────────────────────────────

/// Dispatch matmul: C[M,N] = A[M,K] @ B[K,N]
///
/// B must be stored as [K, N] row-major (stride_bk=N, stride_bn=1).
/// The kernel's vec4 cooperative load requires the N dimension to be contiguous.
///
/// For weight matrices stored as [N, K] (e.g., from GGUF), transpose before calling:
///   `weight.t()?.contiguous()?`
pub fn triton_matmul(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    a: &Tensor,
    b: &Tensor,
    m: usize,
    n: usize,
    k: usize,
    block_m: usize,
    block_n: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (m, n))?;

    with_metal_buffers!(a, b, &out, |a_buf, a_off, b_buf, b_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(a_buf), a_off);
        encoder.set_buffer(1, Some(b_buf), b_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(m as i32));
        encoder.set_bytes(4, &(n as i32));
        encoder.set_bytes(5, &(k as i32));
        encoder.set_bytes(6, &(k as i32));      // stride_am = K
        encoder.set_bytes(7, &1i32);            // stride_ak = 1
        encoder.set_bytes(8, &(n as i32));      // stride_bk = N (B=[K,N], row-major)
        encoder.set_bytes(9, &1i32);            // stride_bn = 1
        encoder.set_bytes(10, &(n as i32));     // stride_cm = N
        encoder.set_bytes(11, &1i32);           // stride_cn = 1

        let grid = MTLSize {
            width: cdiv(m, block_m),
            height: cdiv(n, block_n),
            depth: 1,
        };
        encoder.dispatch_thread_groups(grid, tg_size(pipeline, 1024));
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch matmul + bias: C[M,N] = A[M,K] @ B[K,N] + bias[N]
///
/// B must be [K, N] row-major. Transpose weights before calling.
/// `block_m`/`block_n` must match the compiled kernel tile size.
pub fn triton_matmul_bias(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    a: &Tensor,
    b: &Tensor,
    bias: &Tensor,
    m: usize,
    n: usize,
    k: usize,
    block_m: usize,
    block_n: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (m, n))?;

    with_metal_buffers!(a, b, bias, &out, |a_buf, a_off, b_buf, b_off, bias_buf, bias_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(a_buf), a_off);
        encoder.set_buffer(1, Some(b_buf), b_off);
        encoder.set_buffer(2, Some(bias_buf), bias_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(m as i32));
        encoder.set_bytes(5, &(n as i32));
        encoder.set_bytes(6, &(k as i32));
        encoder.set_bytes(7, &(k as i32));      // stride_am = K
        encoder.set_bytes(8, &1i32);            // stride_ak = 1
        encoder.set_bytes(9, &(n as i32));      // stride_bk = N (B=[K,N])
        encoder.set_bytes(10, &1i32);           // stride_bn = 1
        encoder.set_bytes(11, &(n as i32));     // stride_cm = N
        encoder.set_bytes(12, &1i32);           // stride_cn = 1

        let grid = MTLSize {
            width: cdiv(m, block_m),
            height: cdiv(n, block_n),
            depth: 1,
        };
        encoder.dispatch_thread_groups(grid, tg_size(pipeline, 1024));
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch fused matmul + bias + GELU: C[M,N] = GELU(A[M,K] @ B[K,N] + bias[N])
///
/// B must be [K, N] row-major. Transpose weights before calling.
/// `block_m`/`block_n` must match the compiled kernel tile size.
pub fn triton_matmul_bias_gelu(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    a: &Tensor,
    b: &Tensor,
    bias: &Tensor,
    m: usize,
    n: usize,
    k: usize,
    block_m: usize,
    block_n: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (m, n))?;

    with_metal_buffers!(a, b, bias, &out, |a_buf, a_off, b_buf, b_off, bias_buf, bias_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(a_buf), a_off);
        encoder.set_buffer(1, Some(b_buf), b_off);
        encoder.set_buffer(2, Some(bias_buf), bias_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(m as i32));
        encoder.set_bytes(5, &(n as i32));
        encoder.set_bytes(6, &(k as i32));
        encoder.set_bytes(7, &(k as i32));      // stride_am = K
        encoder.set_bytes(8, &1i32);            // stride_ak = 1
        encoder.set_bytes(9, &(n as i32));      // stride_bk = N (B=[K,N])
        encoder.set_bytes(10, &1i32);           // stride_bn = 1
        encoder.set_bytes(11, &(n as i32));     // stride_cm = N
        encoder.set_bytes(12, &1i32);           // stride_cn = 1

        let grid = MTLSize {
            width: cdiv(m, block_m),
            height: cdiv(n, block_n),
            depth: 1,
        };
        encoder.dispatch_thread_groups(grid, tg_size(pipeline, 1024));
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch unit-offset layernorm: out = LN(x) * (gamma + 1.0)
pub fn triton_layernorm_unit_offset(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    gamma: &Tensor,
    n_rows: usize,
    n_cols: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (n_rows, n_cols))?;

    with_metal_buffers!(x, gamma, &out, |x_buf, x_off, g_buf, g_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(g_buf), g_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_rows as i32));
        encoder.set_bytes(4, &(n_cols as i32));
        encoder.set_bytes(5, &(n_cols as i32));
        encoder.set_bytes(6, &(n_cols as i32));

        let grid = MTLSize { width: n_rows as usize, height: 1, depth: 1 };
        encoder.dispatch_thread_groups(grid, tg_size(pipeline, n_cols));
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch bare layernorm: out = (x - mean) / sqrt(var + eps)
/// No gamma scaling — gamma is baked into downstream weights.
pub fn triton_layernorm_bare(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    n_rows: usize,
    n_cols: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, (n_rows, n_cols))?;

    {
        let (sx, lx) = x.storage_and_layout();
        let (so, lo) = out.storage_and_layout();
        let x_off = lx.start_offset() * x.dtype().size_in_bytes();
        let o_off = lo.start_offset() * out.dtype().size_in_bytes();
        match (&*sx, &*so) {
            (Storage::Metal(mx), Storage::Metal(mo)) => {
                let encoder = device.command_encoder()?;
                encoder.set_compute_pipeline_state(pipeline);
                encoder.set_buffer(0, Some(mx.buffer()), x_off);
                encoder.set_buffer(1, Some(mo.buffer()), o_off);
                encoder.set_bytes(2, &(n_rows as i32));
                encoder.set_bytes(3, &(n_cols as i32));
                encoder.set_bytes(4, &(n_cols as i32));
                encoder.set_bytes(5, &(n_cols as i32));

                let grid = MTLSize { width: n_rows, height: 1, depth: 1 };
                encoder.dispatch_thread_groups(grid, tg_size(pipeline, n_cols));
            }
            _ => anyhow::bail!("Tensors must be on Metal device"),
        }
    }

    Ok(out)
}

/// Dispatch residual add: out = x + residual (element-wise F16)
pub fn triton_residual_add(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    residual: &Tensor,
    n_elements: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, x.shape())?;

    with_metal_buffers!(x, residual, &out, |x_buf, x_off, r_buf, r_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(r_buf), r_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_elements as i32));

        let tg_w = tg_size(pipeline, 1024).width;
        let grid = MTLSize { width: cdiv(n_elements, tg_w) as usize, height: 1, depth: 1 };
        encoder.dispatch_thread_groups(grid, MTLSize { width: tg_w, height: 1, depth: 1 });
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch GELU activation: out[i] = gelu(x[i]) (element-wise F16)
///
/// The kernel processes 1024 elements per threadgroup.
pub fn triton_gelu(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    n_elements: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, x.shape())?;

    {
        let (sx, lx) = x.storage_and_layout();
        let (so, lo) = out.storage_and_layout();
        let x_off = lx.start_offset() * x.dtype().size_in_bytes();
        let o_off = lo.start_offset() * out.dtype().size_in_bytes();
        match (&*sx, &*so) {
            (Storage::Metal(mx), Storage::Metal(mo)) => {
                let encoder = device.command_encoder()?;
                encoder.set_compute_pipeline_state(pipeline);
                encoder.set_buffer(0, Some(mx.buffer()), x_off);
                encoder.set_buffer(1, Some(mo.buffer()), o_off);
                encoder.set_bytes(2, &(n_elements as i32));

                // Kernel hardcodes BLOCK_SIZE=1024
                let grid = MTLSize { width: cdiv(n_elements, 1024), height: 1, depth: 1 };
                encoder.dispatch_thread_groups(grid, tg_size(pipeline, 1024));
            }
            _ => anyhow::bail!("Tensors must be on Metal device"),
        }
    }

    Ok(out)
}

/// Dispatch bias add: out[i] = x[i] + bias[i % n_cols] (element-wise F16)
pub fn triton_bias_add(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor,
    bias: &Tensor,
    n_elements: usize,
    n_cols: usize,
) -> Result<Tensor> {
    let out = empty_f16(device, x.shape())?;

    with_metal_buffers!(x, bias, &out, |x_buf, x_off, b_buf, b_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(b_buf), b_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_elements as i32));
        encoder.set_bytes(4, &(n_cols as i32));

        let tg_w = tg_size(pipeline, 1024).width;
        let grid = MTLSize { width: cdiv(n_elements, tg_w), height: 1, depth: 1 };
        encoder.dispatch_thread_groups(grid, MTLSize { width: tg_w, height: 1, depth: 1 });
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(out)
}

/// Dispatch Flash Attention 2 with sliding window.
///
/// Q, K, V, O: contiguous buffers with same strides.
/// stride_h: offset (in elements) between consecutive heads.
/// stride_m: offset (in elements) between consecutive rows within a head.
/// head_dim must be contiguous (stride 1).
///
/// Common layouts:
///   [n_heads, seq_len, D]: stride_h = seq_len * D, stride_m = D
///   [seq_len, n_heads, D]: stride_h = D, stride_m = n_heads * D
///
/// The kernel fuses QK^T, softmax with sliding window masking, and attn*V
/// in a single pass using online softmax (no materialised seq×seq matrix).
pub fn triton_flash_attention(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    q: &Tensor,
    k: &Tensor,
    v: &Tensor,
    out: &Tensor,
    n_heads: usize,
    seq_len: usize,
    _head_dim: usize,
    stride_h: i32,
    stride_qkv: i32,
    stride_o: i32,
    sm_scale: f32,
    window_left: i32,
    window_right: i32,
) -> Result<()> {
    with_metal_buffers!(q, k, v, out, |q_buf, q_off, k_buf, k_off, v_buf, v_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(q_buf), q_off);
        encoder.set_buffer(1, Some(k_buf), k_off);
        encoder.set_buffer(2, Some(v_buf), v_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(seq_len as i32));
        encoder.set_bytes(5, &stride_h);
        encoder.set_bytes(6, &stride_qkv);
        encoder.set_bytes(7, &stride_o);
        encoder.set_bytes(8, &sm_scale);
        encoder.set_bytes(9, &window_left);
        encoder.set_bytes(10, &window_right);

        let grid = MTLSize {
            width: cdiv(seq_len, 32),
            height: n_heads,
            depth: 1,
        };
        encoder.dispatch_thread_groups(grid, tg_size(pipeline, 832));
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(())
}

/// Create an empty F32 output tensor on the Metal device.
pub fn empty_f32(device: &MetalDevice, shape: impl Into<Shape>) -> Result<Tensor> {
    let shape: Shape = shape.into();
    let n = shape.elem_count();
    let buffer = device.new_buffer(n, DType::F32, "triton_f32_out")?;
    let storage = MetalStorage::new(buffer, device.clone(), n, DType::F32);
    Ok(Tensor::from_storage(
        Storage::Metal(storage),
        shape,
        candle_core::op::BackpropOp::none(),
        false,
    ))
}

/// Dispatch multi-head Flash Attention 2 with precomputed relative position bias.
///
/// Q: [nh, seq_len, d] F16 (Q + bias_u already added)
/// K, V: [nh, seq_len, d] F16
/// bias: [nh, seq_len, seq_len] F16 (unscaled relative position bias)
/// O: [nh, seq_len, d] F16 output
///
/// Kernel computes (QK^T + bias) * scale, then online softmax and attn·V.
/// Multi-head via program_id.y.
pub fn triton_rel_pos_fa2(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    q: &Tensor,
    k: &Tensor,
    v: &Tensor,
    bias: &Tensor,
    out: &Tensor,
    n_heads: usize,
    seq_len: usize,
    head_dim: usize,
    sm_scale: f32,
) -> Result<()> {
    let (sq, lq) = q.storage_and_layout();
    let (sk, lk) = k.storage_and_layout();
    let (sv, lv) = v.storage_and_layout();
    let (sb, lb) = bias.storage_and_layout();
    let (so, lo) = out.storage_and_layout();
    let q_off = lq.start_offset() * q.dtype().size_in_bytes();
    let k_off = lk.start_offset() * k.dtype().size_in_bytes();
    let v_off = lv.start_offset() * v.dtype().size_in_bytes();
    let b_off = lb.start_offset() * bias.dtype().size_in_bytes();
    let o_off = lo.start_offset() * out.dtype().size_in_bytes();

    let stride_h = (seq_len * head_dim) as i32;
    let bias_stride_h = (seq_len * seq_len) as i32;

    match (&*sq, &*sk, &*sv, &*sb, &*so) {
        (Storage::Metal(mq), Storage::Metal(mk), Storage::Metal(mv), Storage::Metal(mb), Storage::Metal(mo)) => {
            let encoder = device.command_encoder()?;
            encoder.set_compute_pipeline_state(pipeline);
            encoder.set_buffer(0, Some(mq.buffer()), q_off);
            encoder.set_buffer(1, Some(mk.buffer()), k_off);
            encoder.set_buffer(2, Some(mv.buffer()), v_off);
            encoder.set_buffer(3, Some(mb.buffer()), b_off);
            encoder.set_buffer(4, Some(mo.buffer()), o_off);
            encoder.set_bytes(5, &(seq_len as i32));
            encoder.set_bytes(6, &(head_dim as i32));
            encoder.set_bytes(7, &sm_scale);
            encoder.set_bytes(8, &stride_h);
            encoder.set_bytes(9, &bias_stride_h);

            let grid = MTLSize {
                width: cdiv(seq_len, 16),  // BM=16
                height: n_heads,
                depth: 1,
            };
            encoder.dispatch_thread_groups(grid, tg_size(pipeline, 512));
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }

    Ok(())
}

// ── Decoder kernel pipelines ─────────────────────────────────────────────────

/// All compiled Triton kernel pipelines for the Moonshine decoder.
pub struct DecoderKernels {
    pub gemv_f16w: ComputePipeline,
    pub gemv_bias_f16w: ComputePipeline,
    pub layernorm_std_f32in: ComputePipeline,
    pub residual_add_f32: ComputePipeline,
    pub convert_f32_to_f16: ComputePipeline,
    pub attention_decode: ComputePipeline,
    pub attention_splitkv_partial: ComputePipeline,
    pub attention_splitkv_reduce: ComputePipeline,
    pub rope_qk_cache_fused: ComputePipeline,
    pub kv_cache_append: ComputePipeline,
    pub glu_silu: ComputePipeline,
    pub residual_add_layernorm: ComputePipeline,
    pub gemv_bias_glu: ComputePipeline,
    pub gemv_resadd_ln: ComputePipeline,
    pub matmul_32x32: ComputePipeline,
    pub gemv_splitk_partial: ComputePipeline,
    pub gemv_splitk_bias_reduce: ComputePipeline,
    pub gemv_splitk_reduce: ComputePipeline,
    pub gemv_splitk_reduce_resadd_ln: ComputePipeline,
    pub gemv_qkv_splitk_partial: ComputePipeline,
    pub gemv_qkv_splitk_reduce: ComputePipeline,
    pub gemv_glu_splitk_partial: ComputePipeline,
    pub gemv_glu_splitk_reduce: ComputePipeline,
}

impl DecoderKernels {
    pub fn load(metal_device: &MetalDevice, kernel_dir: &Path) -> Result<Self> {
        let device = metal_device.device();

        let load = |name: &str, func_name: &str| -> Result<ComputePipeline> {
            eprint!("    {name}...");
            let owned;
            let source = match embedded_metal_source(name) {
                Some(s) => s,
                None => {
                    let path = kernel_dir.join(format!("{name}.metal"));
                    owned = std::fs::read_to_string(&path)
                        .map_err(|e| anyhow::anyhow!("Failed to read {}: {e}", path.display()))?;
                    &owned
                }
            };
            let lib = device
                .new_library_with_source(source, None)
                .map_err(|e| anyhow::anyhow!("Failed to compile {name}: {e}"))?;
            let func = lib
                .get_function(func_name, None)
                .map_err(|e| anyhow::anyhow!("Function {func_name} not found in {name}: {e}"))?;
            let pipeline = device
                .new_compute_pipeline_state_with_function(&func)
                .map_err(|e| anyhow::anyhow!("Pipeline failed for {name}: {e}"))?;
            eprintln!(" ok (max_threads={})", pipeline.max_total_threads_per_threadgroup());
            Ok(pipeline)
        };

        Ok(Self {
            gemv_f16w: load("gemv_f16w", "gemv_f16w")?,
            gemv_bias_f16w: load("gemv_bias_f16w", "gemv_bias_f16w")?,
            layernorm_std_f32in: load("layernorm_standard_f32in_640", "layernorm_standard")?,
            residual_add_f32: load("residual_add_f32", "residual_add_f32")?,
            convert_f32_to_f16: load("convert_f32_to_f16", "convert_f32_to_f16")?,
            attention_decode: load("attention_decode_1d_d80", "attention_decode_1d_masked")?,
            attention_splitkv_partial: load("attention_decode_splitkv_partial", "attention_decode_splitkv_partial")?,
            attention_splitkv_reduce: load("attention_decode_splitkv_reduce", "attention_decode_splitkv_reduce")?,
            rope_qk_cache_fused: load("rope_qk_cache_fused", "rope_qk_cache_fused")?,
            kv_cache_append: load("kv_cache_append", "kv_cache_append")?,
            glu_silu: load("glu_silu_fused", "glu_silu_fused")?,
            residual_add_layernorm: load("residual_add_layernorm_fused", "residual_add_layernorm_fused")?,
            gemv_bias_glu: load("gemv_bias_glu_fused", "gemv_bias_glu_fused")?,
            gemv_resadd_ln: load("gemv_resadd_ln_fused", "gemv_resadd_ln_fused")?,
            matmul_32x32: load("matmul_bias_fp16_32x32x32", "matmul_bias_fp16")?,
            gemv_splitk_partial: load("gemv_splitk_partial", "gemv_splitk_partial")?,
            gemv_splitk_bias_reduce: load("gemv_splitk_bias_reduce", "gemv_splitk_bias_reduce")?,
            gemv_splitk_reduce: load("gemv_splitk_reduce", "gemv_splitk_reduce")?,
            gemv_splitk_reduce_resadd_ln: load("gemv_splitk_reduce_resadd_ln", "gemv_splitk_reduce_resadd_ln")?,
            gemv_qkv_splitk_partial: load("gemv_qkv_splitk_partial", "gemv_qkv_splitk_partial")?,
            gemv_qkv_splitk_reduce: load("gemv_qkv_splitk_reduce", "gemv_qkv_splitk_reduce")?,
            gemv_glu_splitk_partial: load("gemv_glu_splitk_partial", "gemv_glu_splitk_partial")?,
            gemv_glu_splitk_reduce: load("gemv_glu_splitk_reduce", "gemv_glu_splitk_reduce")?,
        })
    }
}

// ── Decoder dispatch functions ───────────────────────────────────────────────

/// GEMV: out_f16[N] = x_f16[K] @ W_f16[K,N]
pub fn triton_gemv_f16w(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, out: &Tensor,
    n: usize, k: usize,
) -> Result<()> {
    with_metal_buffers!(x, w, out, |x_buf, x_off, w_buf, w_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(w_buf), w_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n as i32));
        encoder.set_bytes(4, &(k as i32));
        encoder.set_bytes(5, &1i32);          // stride_wn = 1 (W[K,N])
        encoder.set_bytes(6, &(n as i32));    // stride_wk = N
        let grid_x = cdiv(n, 128);
        encoder.dispatch_thread_groups(
            MTLSize { width: grid_x, height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// GEMV + bias: out_f16[N] = x_f16[K] @ W_f16[K,N] + bias_f32[N]
pub fn triton_gemv_bias_f16w(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, bias: &Tensor, out: &Tensor,
    n: usize, k: usize,
) -> Result<()> {
    with_metal_buffers!(x, w, bias, out, |x_buf, x_off, w_buf, w_off, b_buf, b_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(w_buf), w_off);
        encoder.set_buffer(2, Some(b_buf), b_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(n as i32));
        encoder.set_bytes(5, &(k as i32));
        encoder.set_bytes(6, &1i32);          // stride_wn = 1
        encoder.set_bytes(7, &(n as i32));    // stride_wk = N
        let grid_x = cdiv(n, 128);
        encoder.dispatch_thread_groups(
            MTLSize { width: grid_x, height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// LayerNorm standard with f32 input: out_f16 = LN(x_f32) * weight_f16
pub fn triton_layernorm_std_f32in(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, weight: &Tensor, out: &Tensor,
    n_rows: usize, n_cols: usize,
) -> Result<()> {
    with_metal_buffers!(x, weight, out, |x_buf, x_off, w_buf, w_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(w_buf), w_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_rows as i32));
        encoder.set_bytes(4, &(n_cols as i32));
        encoder.set_bytes(5, &(n_cols as i32)); // stride_x
        encoder.set_bytes(6, &(n_cols as i32)); // stride_out
        encoder.dispatch_thread_groups(
            MTLSize { width: n_rows, height: 1, depth: 1 },
            tg_size(pipeline, 1024),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// Residual add: out_f32 = x_f16 + residual_f32
pub fn triton_residual_add_f32(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, residual: &Tensor, out: &Tensor,
    n_elements: usize,
) -> Result<()> {
    with_metal_buffers!(x, residual, out, |x_buf, x_off, r_buf, r_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(r_buf), r_off);
        encoder.set_buffer(2, Some(o_buf), o_off);
        encoder.set_bytes(3, &(n_elements as i32));
        let grid_x = cdiv(n_elements, 1024);
        encoder.dispatch_thread_groups(
            MTLSize { width: grid_x, height: 1, depth: 1 },
            tg_size(pipeline, 1024),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// Attention decode 1D (masked head_dim, BLOCK_D=128)
pub fn triton_attention_decode(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    q: &Tensor, k: &Tensor, v: &Tensor, out: &Tensor,
    kv_len: usize, head_dim: usize, n_kv_heads: usize, n_q_heads: usize,
    sm_scale: f32, stride_kv_head: usize, stride_kv_seq: usize,
) -> Result<()> {
    with_metal_buffers!(q, k, v, out, |q_buf, q_off, k_buf, k_off, v_buf, v_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(q_buf), q_off);
        encoder.set_buffer(1, Some(k_buf), k_off);
        encoder.set_buffer(2, Some(v_buf), v_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(kv_len as i32));
        encoder.set_bytes(5, &(n_q_heads as i32));
        encoder.set_bytes(6, &(n_kv_heads as i32));
        encoder.set_bytes(7, &sm_scale);
        encoder.set_bytes(8, &(stride_kv_head as i32));
        encoder.set_bytes(9, &(stride_kv_seq as i32));
        encoder.set_bytes(10, &(head_dim as i32));
        encoder.dispatch_thread_groups(
            MTLSize { width: n_q_heads, height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// Fused RoPE(Q) + RoPE(K) + K cache copy
pub fn triton_rope_qk_cache_fused(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    q: &Tensor, k: &Tensor, rope_table: &Tensor, cache_k: &Tensor,
    n_q_heads: usize, n_kv_heads: usize, head_dim: usize,
    half_rot: usize, pos: usize, max_kv_len: usize,
) -> Result<()> {
    with_metal_buffers!(q, k, rope_table, cache_k, |q_buf, q_off, k_buf, k_off, r_buf, r_off, c_buf, c_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(q_buf), q_off);
        encoder.set_buffer(1, Some(k_buf), k_off);
        encoder.set_buffer(2, Some(r_buf), r_off);
        encoder.set_buffer(3, Some(c_buf), c_off);
        encoder.set_bytes(4, &(n_q_heads as i32));
        encoder.set_bytes(5, &(n_kv_heads as i32));
        encoder.set_bytes(6, &(head_dim as i32));
        encoder.set_bytes(7, &(half_rot as i32));
        encoder.set_bytes(8, &(pos as i32));
        encoder.set_bytes(9, &(max_kv_len as i32));
        encoder.dispatch_thread_groups(
            MTLSize { width: 1, height: 1, depth: 1 },
            tg_size(pipeline, 512),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// KV cache append
pub fn triton_kv_cache_append(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    new_kv: &Tensor, cache: &Tensor,
    n_kv_heads: usize, head_dim: usize, max_kv_len: usize, pos: usize,
) -> Result<()> {
    let total_elems = n_kv_heads * head_dim;
    let (s0, l0) = new_kv.storage_and_layout();
    let (s1, l1) = cache.storage_and_layout();
    let off0 = l0.start_offset() * new_kv.dtype().size_in_bytes();
    let off1 = l1.start_offset() * cache.dtype().size_in_bytes();
    match (&*s0, &*s1) {
        (Storage::Metal(m0), Storage::Metal(m1)) => {
            let encoder = device.command_encoder()?;
            encoder.set_compute_pipeline_state(pipeline);
            encoder.set_buffer(0, Some(m0.buffer()), off0);
            encoder.set_buffer(1, Some(m1.buffer()), off1);
            encoder.set_bytes(2, &(total_elems as i32));
            encoder.set_bytes(3, &(max_kv_len as i32));
            encoder.set_bytes(4, &(head_dim as i32));
            encoder.set_bytes(5, &(pos as i32));
            let grid_x = cdiv(total_elems, 256);
            encoder.dispatch_thread_groups(
                MTLSize { width: grid_x, height: 1, depth: 1 },
                tg_size(pipeline, 256),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

/// Fused GLU SiLU: out = SiLU(gate) * x from packed [2*N] buffer
pub fn triton_glu_silu(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    fc1: &Tensor, out: &Tensor,
    n_elements: usize,
) -> Result<()> {
    let (s0, l0) = fc1.storage_and_layout();
    let (s1, l1) = out.storage_and_layout();
    let off0 = l0.start_offset() * fc1.dtype().size_in_bytes();
    let off1 = l1.start_offset() * out.dtype().size_in_bytes();
    match (&*s0, &*s1) {
        (Storage::Metal(m0), Storage::Metal(m1)) => {
            let encoder = device.command_encoder()?;
            encoder.set_compute_pipeline_state(pipeline);
            encoder.set_buffer(0, Some(m0.buffer()), off0);
            encoder.set_buffer(1, Some(m1.buffer()), off1);
            encoder.set_bytes(2, &(n_elements as i32));
            let grid_x = cdiv(n_elements, 1024);
            encoder.dispatch_thread_groups(
                MTLSize { width: grid_x, height: 1, depth: 1 },
                tg_size(pipeline, 1024),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

/// Fused residual-add + layernorm
pub fn triton_residual_add_layernorm(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    f16_proj: &Tensor, f32_residual: &Tensor, f32_out: &Tensor,
    weight: &Tensor, f16_norm: &Tensor,
    n_rows: usize, dim: usize,
) -> Result<()> {
    let (s0, l0) = f16_proj.storage_and_layout();
    let (s1, l1) = f32_residual.storage_and_layout();
    let (s2, l2) = f32_out.storage_and_layout();
    let (s3, l3) = weight.storage_and_layout();
    let (s4, l4) = f16_norm.storage_and_layout();
    let off0 = l0.start_offset() * f16_proj.dtype().size_in_bytes();
    let off1 = l1.start_offset() * f32_residual.dtype().size_in_bytes();
    let off2 = l2.start_offset() * f32_out.dtype().size_in_bytes();
    let off3 = l3.start_offset() * weight.dtype().size_in_bytes();
    let off4 = l4.start_offset() * f16_norm.dtype().size_in_bytes();
    match (&*s0, &*s1, &*s2, &*s3, &*s4) {
        (Storage::Metal(m0), Storage::Metal(m1), Storage::Metal(m2), Storage::Metal(m3), Storage::Metal(m4)) => {
            let encoder = device.command_encoder()?;
            encoder.set_compute_pipeline_state(pipeline);
            encoder.set_buffer(0, Some(m0.buffer()), off0);
            encoder.set_buffer(1, Some(m1.buffer()), off1);
            encoder.set_buffer(2, Some(m2.buffer()), off2);
            encoder.set_buffer(3, Some(m3.buffer()), off3);
            encoder.set_buffer(4, Some(m4.buffer()), off4);
            encoder.set_bytes(5, &(n_rows as i32));
            encoder.set_bytes(6, &(dim as i32));
            encoder.set_bytes(7, &(dim as i32)); // stride_in
            encoder.set_bytes(8, &(dim as i32)); // stride_out
            encoder.dispatch_thread_groups(
                MTLSize { width: n_rows, height: 1, depth: 1 },
                tg_size(pipeline, 1024),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

/// Fused GEMV + bias + GLU-SiLU
pub fn triton_gemv_bias_glu(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, bias: &Tensor, out: &Tensor,
    n_intermediate: usize, k: usize,
) -> Result<()> {
    with_metal_buffers!(x, w, bias, out, |x_buf, x_off, w_buf, w_off, b_buf, b_off, o_buf, o_off| {
        let encoder = device.command_encoder()?;
        encoder.set_compute_pipeline_state(pipeline);
        encoder.set_buffer(0, Some(x_buf), x_off);
        encoder.set_buffer(1, Some(w_buf), w_off);
        encoder.set_buffer(2, Some(b_buf), b_off);
        encoder.set_buffer(3, Some(o_buf), o_off);
        encoder.set_bytes(4, &(n_intermediate as i32));
        encoder.set_bytes(5, &(k as i32));
        encoder.set_bytes(6, &1i32);                               // stride_wn = 1
        encoder.set_bytes(7, &((n_intermediate * 2) as i32));      // stride_wk = 2*N
        let grid_x = cdiv(n_intermediate, 128);
        encoder.dispatch_thread_groups(
            MTLSize { width: grid_x, height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// Fused GEMV + residual-add + layernorm
pub fn triton_gemv_resadd_ln(
    device: &MetalDevice,
    pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor,
    f32_res: &Tensor, f32_out: &Tensor,
    ln_weight: &Tensor, f16_norm: &Tensor,
    dim: usize, gemv_k: usize,
) -> Result<()> {
    let (s0, l0) = x.storage_and_layout();
    let (s1, l1) = w.storage_and_layout();
    let (s2, l2) = f32_res.storage_and_layout();
    let (s3, l3) = f32_out.storage_and_layout();
    let (s4, l4) = ln_weight.storage_and_layout();
    let (s5, l5) = f16_norm.storage_and_layout();
    let off0 = l0.start_offset() * x.dtype().size_in_bytes();
    let off1 = l1.start_offset() * w.dtype().size_in_bytes();
    let off2 = l2.start_offset() * f32_res.dtype().size_in_bytes();
    let off3 = l3.start_offset() * f32_out.dtype().size_in_bytes();
    let off4 = l4.start_offset() * ln_weight.dtype().size_in_bytes();
    let off5 = l5.start_offset() * f16_norm.dtype().size_in_bytes();
    match (&*s0, &*s1, &*s2, &*s3, &*s4, &*s5) {
        (Storage::Metal(m0), Storage::Metal(m1), Storage::Metal(m2), Storage::Metal(m3), Storage::Metal(m4), Storage::Metal(m5)) => {
            let encoder = device.command_encoder()?;
            encoder.set_compute_pipeline_state(pipeline);
            encoder.set_buffer(0, Some(m0.buffer()), off0);
            encoder.set_buffer(1, Some(m1.buffer()), off1);
            encoder.set_buffer(2, Some(m2.buffer()), off2);
            encoder.set_buffer(3, Some(m3.buffer()), off3);
            encoder.set_buffer(4, Some(m4.buffer()), off4);
            encoder.set_buffer(5, Some(m5.buffer()), off5);
            encoder.set_bytes(6, &(dim as i32));
            encoder.set_bytes(7, &(gemv_k as i32));
            encoder.set_bytes(8, &1i32);          // stride_wn = 1
            encoder.set_bytes(9, &(dim as i32));  // stride_wk = dim
            encoder.dispatch_thread_groups(
                MTLSize { width: 1, height: 1, depth: 1 },
                tg_size(pipeline, 1024),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

// ── Batched dispatch (shared encoder) ────────────────────────────────────────
// These variants accept a &ComputeCommandEncoder, allowing ~200 dispatches per
// decoder token to share a single encoder instead of creating one per dispatch.

use candle_metal_kernels::metal::ComputeCommandEncoder;

pub fn enc_gemv_f16w(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, out: &Tensor, n: usize, k: usize,
) -> Result<()> {
    with_metal_buffers!(x, w, out, |x_buf, x_off, w_buf, w_off, o_buf, o_off| {
        enc.set_compute_pipeline_state(pipeline);
        enc.set_buffer(0, Some(x_buf), x_off);
        enc.set_buffer(1, Some(w_buf), w_off);
        enc.set_buffer(2, Some(o_buf), o_off);
        enc.set_bytes(3, &(n as i32));
        enc.set_bytes(4, &(k as i32));
        enc.set_bytes(5, &1i32);
        enc.set_bytes(6, &(n as i32));
        enc.dispatch_thread_groups(
            MTLSize { width: cdiv(n, 128), height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

pub fn enc_gemv_bias_f16w(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, bias: &Tensor, out: &Tensor, n: usize, k: usize,
) -> Result<()> {
    with_metal_buffers!(x, w, bias, out, |x_buf, x_off, w_buf, w_off, b_buf, b_off, o_buf, o_off| {
        enc.set_compute_pipeline_state(pipeline);
        enc.set_buffer(0, Some(x_buf), x_off);
        enc.set_buffer(1, Some(w_buf), w_off);
        enc.set_buffer(2, Some(b_buf), b_off);
        enc.set_buffer(3, Some(o_buf), o_off);
        enc.set_bytes(4, &(n as i32));
        enc.set_bytes(5, &(k as i32));
        enc.set_bytes(6, &1i32);
        enc.set_bytes(7, &(n as i32));
        enc.dispatch_thread_groups(
            MTLSize { width: cdiv(n, 128), height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

pub fn enc_layernorm_std_f32in(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &Tensor, weight: &Tensor, out: &Tensor, n_rows: usize, n_cols: usize,
) -> Result<()> {
    with_metal_buffers!(x, weight, out, |x_buf, x_off, w_buf, w_off, o_buf, o_off| {
        enc.set_compute_pipeline_state(pipeline);
        enc.set_buffer(0, Some(x_buf), x_off);
        enc.set_buffer(1, Some(w_buf), w_off);
        enc.set_buffer(2, Some(o_buf), o_off);
        enc.set_bytes(3, &(n_rows as i32));
        enc.set_bytes(4, &(n_cols as i32));
        enc.set_bytes(5, &(n_cols as i32));
        enc.set_bytes(6, &(n_cols as i32));
        enc.dispatch_thread_groups(
            MTLSize { width: n_rows, height: 1, depth: 1 },
            tg_size(pipeline, 1024),
        );
        Ok::<(), anyhow::Error>(())
    })
}

pub fn enc_attention_decode(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    q: &Tensor, k: &Tensor, v: &Tensor, out: &Tensor,
    kv_len: usize, head_dim: usize, n_kv_heads: usize, n_q_heads: usize,
    sm_scale: f32, stride_kv_head: usize, stride_kv_seq: usize,
) -> Result<()> {
    with_metal_buffers!(q, k, v, out, |q_buf, q_off, k_buf, k_off, v_buf, v_off, o_buf, o_off| {
        enc.set_compute_pipeline_state(pipeline);
        enc.set_buffer(0, Some(q_buf), q_off);
        enc.set_buffer(1, Some(k_buf), k_off);
        enc.set_buffer(2, Some(v_buf), v_off);
        enc.set_buffer(3, Some(o_buf), o_off);
        enc.set_bytes(4, &(kv_len as i32));
        enc.set_bytes(5, &(n_q_heads as i32));
        enc.set_bytes(6, &(n_kv_heads as i32));
        enc.set_bytes(7, &sm_scale);
        enc.set_bytes(8, &(stride_kv_head as i32));
        enc.set_bytes(9, &(stride_kv_seq as i32));
        enc.set_bytes(10, &(head_dim as i32));
        enc.dispatch_thread_groups(
            MTLSize { width: n_q_heads, height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

pub fn enc_attention_splitkv(
    enc: &ComputeCommandEncoder,
    partial_pipeline: &ComputePipeline, reduce_pipeline: &ComputePipeline,
    q: &Tensor, k: &Tensor, v: &Tensor, out: &Tensor, partial_buf: &Tensor,
    kv_len: usize, head_dim: usize, n_kv_heads: usize, n_q_heads: usize,
    sm_scale: f32, stride_kv_head: usize, stride_kv_seq: usize,
    n_splits: usize,
) -> Result<()> {
    let kv_per_split = (kv_len + n_splits - 1) / n_splits;
    let block_d = 128usize;
    let stride_partial = 3 * block_d;

    // Phase 1: partial attention per (head, split)
    // Need 4 buffers: q, k, v, partial — use nested extraction
    let (sq, lq) = q.storage_and_layout();
    let (sk, lk) = k.storage_and_layout();
    let (sv, lv) = v.storage_and_layout();
    let (sp, lp) = partial_buf.storage_and_layout();
    let q_off = lq.start_offset() * q.dtype().size_in_bytes();
    let k_off = lk.start_offset() * k.dtype().size_in_bytes();
    let v_off = lv.start_offset() * v.dtype().size_in_bytes();
    let p_off = lp.start_offset() * partial_buf.dtype().size_in_bytes();
    match (&*sq, &*sk, &*sv, &*sp) {
        (Storage::Metal(mq), Storage::Metal(mk), Storage::Metal(mv), Storage::Metal(mp)) => {
            enc.set_compute_pipeline_state(partial_pipeline);
            enc.set_buffer(0, Some(mq.buffer()), q_off);
            enc.set_buffer(1, Some(mk.buffer()), k_off);
            enc.set_buffer(2, Some(mv.buffer()), v_off);
            enc.set_buffer(3, Some(mp.buffer()), p_off);
            enc.set_bytes(4, &(kv_len as i32));
            enc.set_bytes(5, &(n_q_heads as i32));
            enc.set_bytes(6, &(n_kv_heads as i32));
            enc.set_bytes(7, &sm_scale);
            enc.set_bytes(8, &(stride_kv_head as i32));
            enc.set_bytes(9, &(stride_kv_seq as i32));
            enc.set_bytes(10, &(head_dim as i32));
            enc.set_bytes(11, &(n_splits as i32));
            enc.set_bytes(12, &(kv_per_split as i32));
            enc.set_bytes(13, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_q_heads * n_splits, height: 1, depth: 1 },
                tg_size(partial_pipeline, 128),
            );
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
    drop(sq); drop(sk); drop(sv); drop(sp);

    // Phase 2: reduce partials to final output
    let (sp2, lp2) = partial_buf.storage_and_layout();
    let (so, lo) = out.storage_and_layout();
    let p_off2 = lp2.start_offset() * partial_buf.dtype().size_in_bytes();
    let o_off = lo.start_offset() * out.dtype().size_in_bytes();
    match (&*sp2, &*so) {
        (Storage::Metal(mp2), Storage::Metal(mo)) => {
            enc.set_compute_pipeline_state(reduce_pipeline);
            enc.set_buffer(0, Some(mp2.buffer()), p_off2);
            enc.set_buffer(1, Some(mo.buffer()), o_off);
            enc.set_bytes(2, &(n_q_heads as i32));
            enc.set_bytes(3, &(n_splits as i32));
            enc.set_bytes(4, &(head_dim as i32));
            enc.set_bytes(5, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_q_heads, height: 1, depth: 1 },
                tg_size(reduce_pipeline, 128),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

pub fn enc_rope_qk_cache_fused(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    q: &Tensor, k: &Tensor, rope_table: &Tensor, cache_k: &Tensor,
    n_q_heads: usize, n_kv_heads: usize, head_dim: usize,
    half_rot: usize, pos: usize, max_kv_len: usize,
) -> Result<()> {
    with_metal_buffers!(q, k, rope_table, cache_k, |q_buf, q_off, k_buf, k_off, r_buf, r_off, c_buf, c_off| {
        enc.set_compute_pipeline_state(pipeline);
        enc.set_buffer(0, Some(q_buf), q_off);
        enc.set_buffer(1, Some(k_buf), k_off);
        enc.set_buffer(2, Some(r_buf), r_off);
        enc.set_buffer(3, Some(c_buf), c_off);
        enc.set_bytes(4, &(n_q_heads as i32));
        enc.set_bytes(5, &(n_kv_heads as i32));
        enc.set_bytes(6, &(head_dim as i32));
        enc.set_bytes(7, &(half_rot as i32));
        enc.set_bytes(8, &(pos as i32));
        enc.set_bytes(9, &(max_kv_len as i32));
        enc.dispatch_thread_groups(
            MTLSize { width: 1, height: 1, depth: 1 },
            tg_size(pipeline, 512),
        );
        Ok::<(), anyhow::Error>(())
    })
}

pub fn enc_kv_cache_append(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    new_kv: &Tensor, cache: &Tensor,
    n_kv_heads: usize, head_dim: usize, max_kv_len: usize, pos: usize,
) -> Result<()> {
    let total_elems = n_kv_heads * head_dim;
    let (s0, l0) = new_kv.storage_and_layout();
    let (s1, l1) = cache.storage_and_layout();
    let off0 = l0.start_offset() * new_kv.dtype().size_in_bytes();
    let off1 = l1.start_offset() * cache.dtype().size_in_bytes();
    match (&*s0, &*s1) {
        (Storage::Metal(m0), Storage::Metal(m1)) => {
            enc.set_compute_pipeline_state(pipeline);
            enc.set_buffer(0, Some(m0.buffer()), off0);
            enc.set_buffer(1, Some(m1.buffer()), off1);
            enc.set_bytes(2, &(total_elems as i32));
            enc.set_bytes(3, &(max_kv_len as i32));
            enc.set_bytes(4, &(head_dim as i32));
            enc.set_bytes(5, &(pos as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: cdiv(total_elems, 256), height: 1, depth: 1 },
                tg_size(pipeline, 256),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

pub fn enc_residual_add_layernorm(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    f16_proj: &Tensor, f32_residual: &Tensor, f32_out: &Tensor,
    weight: &Tensor, f16_norm: &Tensor,
    n_rows: usize, dim: usize,
) -> Result<()> {
    let (s0, l0) = f16_proj.storage_and_layout();
    let (s1, l1) = f32_residual.storage_and_layout();
    let (s2, l2) = f32_out.storage_and_layout();
    let (s3, l3) = weight.storage_and_layout();
    let (s4, l4) = f16_norm.storage_and_layout();
    let off0 = l0.start_offset() * f16_proj.dtype().size_in_bytes();
    let off1 = l1.start_offset() * f32_residual.dtype().size_in_bytes();
    let off2 = l2.start_offset() * f32_out.dtype().size_in_bytes();
    let off3 = l3.start_offset() * weight.dtype().size_in_bytes();
    let off4 = l4.start_offset() * f16_norm.dtype().size_in_bytes();
    match (&*s0, &*s1, &*s2, &*s3, &*s4) {
        (Storage::Metal(m0), Storage::Metal(m1), Storage::Metal(m2), Storage::Metal(m3), Storage::Metal(m4)) => {
            enc.set_compute_pipeline_state(pipeline);
            enc.set_buffer(0, Some(m0.buffer()), off0);
            enc.set_buffer(1, Some(m1.buffer()), off1);
            enc.set_buffer(2, Some(m2.buffer()), off2);
            enc.set_buffer(3, Some(m3.buffer()), off3);
            enc.set_buffer(4, Some(m4.buffer()), off4);
            enc.set_bytes(5, &(n_rows as i32));
            enc.set_bytes(6, &(dim as i32));
            enc.set_bytes(7, &(dim as i32));
            enc.set_bytes(8, &(dim as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_rows, height: 1, depth: 1 },
                tg_size(pipeline, 1024),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

pub fn enc_gemv_bias_glu(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, bias: &Tensor, out: &Tensor,
    n_intermediate: usize, k: usize,
) -> Result<()> {
    with_metal_buffers!(x, w, bias, out, |x_buf, x_off, w_buf, w_off, b_buf, b_off, o_buf, o_off| {
        enc.set_compute_pipeline_state(pipeline);
        enc.set_buffer(0, Some(x_buf), x_off);
        enc.set_buffer(1, Some(w_buf), w_off);
        enc.set_buffer(2, Some(b_buf), b_off);
        enc.set_buffer(3, Some(o_buf), o_off);
        enc.set_bytes(4, &(n_intermediate as i32));
        enc.set_bytes(5, &(k as i32));
        enc.set_bytes(6, &1i32);
        enc.set_bytes(7, &((n_intermediate * 2) as i32));
        enc.dispatch_thread_groups(
            MTLSize { width: cdiv(n_intermediate, 128), height: 1, depth: 1 },
            tg_size(pipeline, 128),
        );
        Ok::<(), anyhow::Error>(())
    })
}

/// K-split GEMV + bias for fc2: split K across multiple threadgroups, then reduce.
pub fn enc_gemv_splitk_bias(
    enc: &ComputeCommandEncoder,
    partial_pipeline: &ComputePipeline, reduce_pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, bias: &Tensor, out: &Tensor, partial_buf: &Tensor,
    n: usize, k: usize, n_splits: usize,
) -> Result<()> {
    let k_per_split = k / n_splits;
    let n_n_blocks = cdiv(n, 128);
    let stride_wk = n;        // [K, N] layout
    let stride_partial = n;   // [n_splits, N]

    let (s0, l0) = x.storage_and_layout();
    let (s1, l1) = w.storage_and_layout();
    let (s2, l2) = bias.storage_and_layout();
    let (s3, l3) = out.storage_and_layout();
    let (s4, l4) = partial_buf.storage_and_layout();
    let off0 = l0.start_offset() * x.dtype().size_in_bytes();
    let off1 = l1.start_offset() * w.dtype().size_in_bytes();
    let off2 = l2.start_offset() * bias.dtype().size_in_bytes();
    let off3 = l3.start_offset() * out.dtype().size_in_bytes();
    let off4 = l4.start_offset() * partial_buf.dtype().size_in_bytes();
    match (&*s0, &*s1, &*s2, &*s3, &*s4) {
        (Storage::Metal(m0), Storage::Metal(m1), Storage::Metal(m2), Storage::Metal(m3), Storage::Metal(m4)) => {
            // Phase 1: partial GEMV
            enc.set_compute_pipeline_state(partial_pipeline);
            enc.set_buffer(0, Some(m0.buffer()), off0);
            enc.set_buffer(1, Some(m1.buffer()), off1);
            enc.set_buffer(2, Some(m4.buffer()), off4);
            enc.set_bytes(3, &(n as i32));
            enc.set_bytes(4, &(k as i32));
            enc.set_bytes(5, &(stride_wk as i32));
            enc.set_bytes(6, &(n_n_blocks as i32));
            enc.set_bytes(7, &(k_per_split as i32));
            enc.set_bytes(8, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_n_blocks * n_splits, height: 1, depth: 1 },
                tg_size(partial_pipeline, 128),
            );
            // Phase 2: reduce + bias
            enc.set_compute_pipeline_state(reduce_pipeline);
            enc.set_buffer(0, Some(m4.buffer()), off4);
            enc.set_buffer(1, Some(m2.buffer()), off2);
            enc.set_buffer(2, Some(m3.buffer()), off3);
            enc.set_bytes(3, &(n as i32));
            enc.set_bytes(4, &(n_splits as i32));
            enc.set_bytes(5, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_n_blocks, height: 1, depth: 1 },
                tg_size(reduce_pipeline, 128),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

/// K-split GEMV (no bias) for Q/K/V/O projections: split K across threadgroups, then reduce.
pub fn enc_gemv_splitk(
    enc: &ComputeCommandEncoder,
    partial_pipeline: &ComputePipeline, reduce_pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, out: &Tensor, partial_buf: &Tensor,
    n: usize, k: usize, n_splits: usize,
) -> Result<()> {
    let k_per_split = k / n_splits;
    let n_n_blocks = cdiv(n, 128);
    let stride_wk = n;        // [K, N] layout
    let stride_partial = n;   // [n_splits, N]

    let (s0, l0) = x.storage_and_layout();
    let (s1, l1) = w.storage_and_layout();
    let (s2, l2) = out.storage_and_layout();
    let (s3, l3) = partial_buf.storage_and_layout();
    let off0 = l0.start_offset() * x.dtype().size_in_bytes();
    let off1 = l1.start_offset() * w.dtype().size_in_bytes();
    let off2 = l2.start_offset() * out.dtype().size_in_bytes();
    let off3 = l3.start_offset() * partial_buf.dtype().size_in_bytes();
    match (&*s0, &*s1, &*s2, &*s3) {
        (Storage::Metal(m0), Storage::Metal(m1), Storage::Metal(m2), Storage::Metal(m3)) => {
            // Phase 1: partial GEMV
            enc.set_compute_pipeline_state(partial_pipeline);
            enc.set_buffer(0, Some(m0.buffer()), off0);
            enc.set_buffer(1, Some(m1.buffer()), off1);
            enc.set_buffer(2, Some(m3.buffer()), off3);
            enc.set_bytes(3, &(n as i32));
            enc.set_bytes(4, &(k as i32));
            enc.set_bytes(5, &(stride_wk as i32));
            enc.set_bytes(6, &(n_n_blocks as i32));
            enc.set_bytes(7, &(k_per_split as i32));
            enc.set_bytes(8, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_n_blocks * n_splits, height: 1, depth: 1 },
                tg_size(partial_pipeline, 128),
            );
            // Phase 2: reduce (no bias)
            enc.set_compute_pipeline_state(reduce_pipeline);
            enc.set_buffer(0, Some(m3.buffer()), off3);
            enc.set_buffer(1, Some(m2.buffer()), off2);
            enc.set_bytes(2, &(n as i32));
            enc.set_bytes(3, &(n_splits as i32));
            enc.set_bytes(4, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_n_blocks, height: 1, depth: 1 },
                tg_size(reduce_pipeline, 128),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

/// Split-K GEMV + fused reduce + residual-add + layernorm.
/// Phase 1: partial GEMV (many TGs), Phase 2: reduce + resadd + LN (1 TG).
pub fn enc_gemv_splitk_resadd_ln(
    enc: &ComputeCommandEncoder,
    partial_pipeline: &ComputePipeline, fused_pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor,
    residual: &Tensor, out_f32: &Tensor,
    ln_weight: &Tensor, norm_out: &Tensor,
    partial_buf: &Tensor,
    dim: usize, k: usize, n_splits: usize,
) -> Result<()> {
    let k_per_split = k / n_splits;
    let n_n_blocks = cdiv(dim, 128);
    let stride_wk = dim;
    let stride_partial = dim;

    let (s0, l0) = x.storage_and_layout();
    let (s1, l1) = w.storage_and_layout();
    let (s2, l2) = residual.storage_and_layout();
    let (s3, l3) = out_f32.storage_and_layout();
    let (s4, l4) = ln_weight.storage_and_layout();
    let (s5, l5) = norm_out.storage_and_layout();
    let (s6, l6) = partial_buf.storage_and_layout();
    let off0 = l0.start_offset() * x.dtype().size_in_bytes();
    let off1 = l1.start_offset() * w.dtype().size_in_bytes();
    let off2 = l2.start_offset() * residual.dtype().size_in_bytes();
    let off3 = l3.start_offset() * out_f32.dtype().size_in_bytes();
    let off4 = l4.start_offset() * ln_weight.dtype().size_in_bytes();
    let off5 = l5.start_offset() * norm_out.dtype().size_in_bytes();
    let off6 = l6.start_offset() * partial_buf.dtype().size_in_bytes();
    match (&*s0, &*s1, &*s2, &*s3, &*s4, &*s5, &*s6) {
        (Storage::Metal(m0), Storage::Metal(m1), Storage::Metal(m2), Storage::Metal(m3),
         Storage::Metal(m4), Storage::Metal(m5), Storage::Metal(m6)) => {
            // Phase 1: partial GEMV
            enc.set_compute_pipeline_state(partial_pipeline);
            enc.set_buffer(0, Some(m0.buffer()), off0);
            enc.set_buffer(1, Some(m1.buffer()), off1);
            enc.set_buffer(2, Some(m6.buffer()), off6);
            enc.set_bytes(3, &(dim as i32));
            enc.set_bytes(4, &(k as i32));
            enc.set_bytes(5, &(stride_wk as i32));
            enc.set_bytes(6, &(n_n_blocks as i32));
            enc.set_bytes(7, &(k_per_split as i32));
            enc.set_bytes(8, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_n_blocks * n_splits, height: 1, depth: 1 },
                tg_size(partial_pipeline, 128),
            );
            // Phase 2: fused reduce + resadd + LN (1 threadgroup)
            enc.set_compute_pipeline_state(fused_pipeline);
            enc.set_buffer(0, Some(m6.buffer()), off6);
            enc.set_buffer(1, Some(m2.buffer()), off2);
            enc.set_buffer(2, Some(m3.buffer()), off3);
            enc.set_buffer(3, Some(m4.buffer()), off4);
            enc.set_buffer(4, Some(m5.buffer()), off5);
            enc.set_bytes(5, &(dim as i32));
            enc.set_bytes(6, &(n_splits as i32));
            enc.set_bytes(7, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: 1, height: 1, depth: 1 },
                tg_size(fused_pipeline, 1024),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

/// Fused Q/K/V split-K GEMV: single dispatch for all 3 projections.
pub fn enc_gemv_qkv_splitk(
    enc: &ComputeCommandEncoder,
    partial_pipeline: &ComputePipeline, reduce_pipeline: &ComputePipeline,
    x: &Tensor, wq: &Tensor, wk: &Tensor, wv: &Tensor,
    oq: &Tensor, ok: &Tensor, ov: &Tensor,
    partial_buf: &Tensor,
    n: usize, k: usize, n_splits: usize,
) -> Result<()> {
    let k_per_split = k / n_splits;
    let n_n_blocks = cdiv(n, 128);
    let stride_wk = n;
    let stride_partial = n;

    let (sx, lx) = x.storage_and_layout();
    let (sq, lq) = wq.storage_and_layout();
    let (sk, lk) = wk.storage_and_layout();
    let (sv, lv) = wv.storage_and_layout();
    let (soq, loq) = oq.storage_and_layout();
    let (sok, lok) = ok.storage_and_layout();
    let (sov, lov) = ov.storage_and_layout();
    let (sp, lp) = partial_buf.storage_and_layout();
    let ox = lx.start_offset() * x.dtype().size_in_bytes();
    let oq_off = lq.start_offset() * wq.dtype().size_in_bytes();
    let ok_off = lk.start_offset() * wk.dtype().size_in_bytes();
    let ov_off = lv.start_offset() * wv.dtype().size_in_bytes();
    let ooq = loq.start_offset() * oq.dtype().size_in_bytes();
    let ook = lok.start_offset() * ok.dtype().size_in_bytes();
    let oov = lov.start_offset() * ov.dtype().size_in_bytes();
    let op = lp.start_offset() * partial_buf.dtype().size_in_bytes();
    match (&*sx, &*sq, &*sk, &*sv, &*soq, &*sok, &*sov, &*sp) {
        (Storage::Metal(mx), Storage::Metal(mq), Storage::Metal(mk), Storage::Metal(mv),
         Storage::Metal(moq), Storage::Metal(mok), Storage::Metal(mov), Storage::Metal(mp)) => {
            // Phase 1: fused QKV partial (grid: n_n_blocks*n_splits × 3)
            enc.set_compute_pipeline_state(partial_pipeline);
            enc.set_buffer(0, Some(mx.buffer()), ox);
            enc.set_buffer(1, Some(mq.buffer()), oq_off);
            enc.set_buffer(2, Some(mk.buffer()), ok_off);
            enc.set_buffer(3, Some(mv.buffer()), ov_off);
            enc.set_buffer(4, Some(mp.buffer()), op);
            enc.set_bytes(5, &(n as i32));
            enc.set_bytes(6, &(k as i32));
            enc.set_bytes(7, &(stride_wk as i32));
            enc.set_bytes(8, &(n_n_blocks as i32));
            enc.set_bytes(9, &(k_per_split as i32));
            enc.set_bytes(10, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_n_blocks * n_splits, height: 3, depth: 1 },
                tg_size(partial_pipeline, 128),
            );
            // Phase 2: fused QKV reduce (grid: cdiv(N,128) × 3)
            enc.set_compute_pipeline_state(reduce_pipeline);
            enc.set_buffer(0, Some(mp.buffer()), op);
            enc.set_buffer(1, Some(moq.buffer()), ooq);
            enc.set_buffer(2, Some(mok.buffer()), ook);
            enc.set_buffer(3, Some(mov.buffer()), oov);
            enc.set_bytes(4, &(n as i32));
            enc.set_bytes(5, &(n_splits as i32));
            enc.set_bytes(6, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_n_blocks, height: 3, depth: 1 },
                tg_size(reduce_pipeline, 128),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

/// K-split GEMV + GLU-SiLU + bias for fc1: split K across threadgroups, then reduce with GLU.
pub fn enc_gemv_glu_splitk(
    enc: &ComputeCommandEncoder,
    partial_pipeline: &ComputePipeline, reduce_pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor, bias: &Tensor, out: &Tensor, partial_buf: &Tensor,
    n_intermediate: usize, k: usize, n_splits: usize,
) -> Result<()> {
    let k_per_split = k / n_splits;
    let n_n_blocks = cdiv(n_intermediate, 128);
    let stride_wk = n_intermediate * 2;    // [2*N, K] layout
    let stride_partial = n_intermediate * 2; // [n_splits, 2*N]

    let (s0, l0) = x.storage_and_layout();
    let (s1, l1) = w.storage_and_layout();
    let (s2, l2) = bias.storage_and_layout();
    let (s3, l3) = out.storage_and_layout();
    let (s4, l4) = partial_buf.storage_and_layout();
    let off0 = l0.start_offset() * x.dtype().size_in_bytes();
    let off1 = l1.start_offset() * w.dtype().size_in_bytes();
    let off2 = l2.start_offset() * bias.dtype().size_in_bytes();
    let off3 = l3.start_offset() * out.dtype().size_in_bytes();
    let off4 = l4.start_offset() * partial_buf.dtype().size_in_bytes();
    match (&*s0, &*s1, &*s2, &*s3, &*s4) {
        (Storage::Metal(m0), Storage::Metal(m1), Storage::Metal(m2), Storage::Metal(m3), Storage::Metal(m4)) => {
            // Phase 1: partial GEMV (x-half + gate-half)
            enc.set_compute_pipeline_state(partial_pipeline);
            enc.set_buffer(0, Some(m0.buffer()), off0);
            enc.set_buffer(1, Some(m1.buffer()), off1);
            enc.set_buffer(2, Some(m4.buffer()), off4);
            enc.set_bytes(3, &(n_intermediate as i32));
            enc.set_bytes(4, &(k as i32));
            enc.set_bytes(5, &(stride_wk as i32));
            enc.set_bytes(6, &(n_n_blocks as i32));
            enc.set_bytes(7, &(k_per_split as i32));
            enc.set_bytes(8, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_n_blocks * n_splits, height: 1, depth: 1 },
                tg_size(partial_pipeline, 128),
            );
            // Phase 2: reduce + bias + GLU-SiLU
            enc.set_compute_pipeline_state(reduce_pipeline);
            enc.set_buffer(0, Some(m4.buffer()), off4);
            enc.set_buffer(1, Some(m2.buffer()), off2);
            enc.set_buffer(2, Some(m3.buffer()), off3);
            enc.set_bytes(3, &(n_intermediate as i32));
            enc.set_bytes(4, &(n_splits as i32));
            enc.set_bytes(5, &(stride_partial as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: n_n_blocks, height: 1, depth: 1 },
                tg_size(reduce_pipeline, 128),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

pub fn enc_gemv_resadd_ln(
    enc: &ComputeCommandEncoder, pipeline: &ComputePipeline,
    x: &Tensor, w: &Tensor,
    f32_res: &Tensor, f32_out: &Tensor,
    ln_weight: &Tensor, f16_norm: &Tensor,
    dim: usize, gemv_k: usize,
) -> Result<()> {
    let (s0, l0) = x.storage_and_layout();
    let (s1, l1) = w.storage_and_layout();
    let (s2, l2) = f32_res.storage_and_layout();
    let (s3, l3) = f32_out.storage_and_layout();
    let (s4, l4) = ln_weight.storage_and_layout();
    let (s5, l5) = f16_norm.storage_and_layout();
    let off0 = l0.start_offset() * x.dtype().size_in_bytes();
    let off1 = l1.start_offset() * w.dtype().size_in_bytes();
    let off2 = l2.start_offset() * f32_res.dtype().size_in_bytes();
    let off3 = l3.start_offset() * f32_out.dtype().size_in_bytes();
    let off4 = l4.start_offset() * ln_weight.dtype().size_in_bytes();
    let off5 = l5.start_offset() * f16_norm.dtype().size_in_bytes();
    match (&*s0, &*s1, &*s2, &*s3, &*s4, &*s5) {
        (Storage::Metal(m0), Storage::Metal(m1), Storage::Metal(m2), Storage::Metal(m3), Storage::Metal(m4), Storage::Metal(m5)) => {
            enc.set_compute_pipeline_state(pipeline);
            enc.set_buffer(0, Some(m0.buffer()), off0);
            enc.set_buffer(1, Some(m1.buffer()), off1);
            enc.set_buffer(2, Some(m2.buffer()), off2);
            enc.set_buffer(3, Some(m3.buffer()), off3);
            enc.set_buffer(4, Some(m4.buffer()), off4);
            enc.set_buffer(5, Some(m5.buffer()), off5);
            enc.set_bytes(6, &(dim as i32));
            enc.set_bytes(7, &(gemv_k as i32));
            enc.set_bytes(8, &1i32);
            enc.set_bytes(9, &(dim as i32));
            enc.dispatch_thread_groups(
                MTLSize { width: 1, height: 1, depth: 1 },
                tg_size(pipeline, 1024),
            );
            Ok(())
        }
        _ => anyhow::bail!("All tensors must be on Metal device"),
    }
}

/// Default kernel directory.
/// On x86_64 (Intel Mac), uses moonshine_metal_intel (scalar codegen, no simdgroup_matrix).
/// On aarch64 (Apple Silicon), uses moonshine_metal (simdgroup_matrix optimized).
pub fn default_kernel_dir() -> PathBuf {
    let subdir = if cfg!(target_arch = "x86_64") {
        "moonshine_metal_intel"
    } else {
        "moonshine_metal"
    };
    let triton_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join(format!("triton/third_party/metal/{subdir}"));
    if triton_dir.exists() {
        return triton_dir;
    }
    PathBuf::from(subdir)
}
